### ISSUE TITLE
 RAR5 "EXTRACTION ERROR"+ JDOWNLOAD + DOCKER + OMV 4

### ISSUE THREAD

**Issue by Loik419** [jaymoulin/docker-jdownloader#10]
Hello,
 
I installed OMV4 with DOCKER and JDOWNLOADER / JAYMOULIN.
 
There is a problem with decompressing RAR version 5 files: https://board.jdownloader.org/showthread.php?s=31165b449fca85693b2fbf0ebd544fbc&t=71069 

It puts me "EXTRACTION ERROR".
 
To update JDOWNLOADER, I need to put the file in the JDOWNLOADER / LIBS folder but I do not know how to do it on DOCKER and JDOWNLOADER.
 
Example file to test it:
https://mega.nz/#!Sw8FAQAA!VC7PkyT299UHEj5u5Xs2STfpDjqzEktG51NKixGqflM

Do you know how to do it ?

**Comment by jaymoulin** [comment]
just `docker pull jaymoulin/jdownlaoder` and recreate you container to add RAR5 support

**Comment by Loik419** [comment]
Thanks for the information. I removed the container and reinstalled a new "jaymoulin / jdownloader" container.
The archive extractor is activated but when I right click on the file downloaded via myJDownloader, "archive setting" is disabled.

**Comment by henningBunk** [comment]
I've got the same problem.

**Comment by jaymoulin** [comment]
I don't reproduce your greyed archive settings option. But if you thing this is related to this docker image AND NOT jdownloader (I am not part of jdownloader support), Then please open a pecific issue with detailed steps to reproduce.
