### ISSUE TITLE
 java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by karl0ss** [jaymoulin/docker-jdownloader#103]
Running on Raspberry Pi 4 running Debian,

This has been running for...months, maybe even years without any trouble..but this morning seems to have run an update and now JD won't start, due to -

<details>
<pre>
1|Log.L.log 12/3/21 1:33:32 PM - INFO [ jd.SecondLevelLaunch(mainStart) ] -> Hardware detected:RaspberryPI|Type:4B|MemorySize:GB_4|Manufacturer:SONY_UK|Processor:BCM2711|Raw:c03111
--- I'VE REMOVED A NUMBER OF LINES LIKE -
17|Log.L.log 12/3/21 1:33:37 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> CFG File does not exist: /opt/JDownloader/app/cfg/plugins/HOSTER/vidlox.me.json
-----
25|Log.L.log 12/3/21 1:33:42 PM - SEVERE [ Log.L.log ] -> Exception thrown at jd.SecondLevelLaunch$9$1.run(SecondLevelLaunch.java:919):
java.lang.ExceptionInInitializerError
	at jd.SecondLevelLaunch$9$1.run(SecondLevelLaunch.java:747)
Caused by: java.lang.RuntimeException: No Console Available!
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.askLoginsOnConsole(MyJDownloaderController.java:273)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:125)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:112)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:37)
	... 1 more
THREAD: 30
30|Log.L.log 12/3/21 1:33:43 PM - INFO [ jd.config.SubConfiguration(save) ] -> Save Name:imgur.com|SetMark:2|File:/opt/JDownloader/app/cfg/subconf_imgur.com.ejs
</pre>
</details>

Hope you have some ideas for me.

Thanks

**Comment by quorn23** [comment]
`THREAD: 291,
291|Log.L.log 12/3/21 4:06:19 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/app/cfg/jd.controlling.faviconcontroller.FavIconsConfig.failedhosts.json,
#,
# A fatal error has been detected by the Java Runtime Environment:,
#,
#  SIGSEGV (0xb) at pc=0x00007f7f8a495cf4, pid=38, tid=0x00007f7f63fff700,
#,
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10),
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops),
# Problematic frame:,
# C  [libc.so.6+0x106cf4]  __clock_gettime+0x24,
#,
# Core dump written. Default location: /opt/JDownloader/core or core.38,
#,
# An error report file with more information is saved as:,
# /opt/JDownloader/hs_err_pid38.log`

for me the whole app just crashes. Let me know if it's not the same issue and i'll open one.
Running the :latest tag (2.0.1) from the update a few hours ago.

Running on an ubuntu server 20.04.3 LTS and Docker 20.10.11

**Comment by BelphegorPrime** [comment]
got the same error as @quorn23.
Deleted my old config directory. Same Issue.
After adding `- /etc/localtime:/etc/localtime:ro #optional` volume, I get the following error when I want to add an account for example or add an download.

```
 

#

# A fatal error has been detected by the Java Runtime Environment:

#

#  SIGSEGV (0xb) at pc=0x00007efefa9d0020, pid=37, tid=0x00007efe3b2f8700

#

# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)

# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)

# Problematic frame:

# C  [libc.so.6+0x7d020]  _IO_link_in+0x250

#

# Core dump written. Default location: /opt/JDownloader/core or core.37

#

# An error report file with more information is saved as:



```

**Comment by karl0ss** [comment]
@jaymoulin, the log I gave you is after removing and letting it rebuild the config directory, thought I would try that before contact you.

**Comment by gadric** [comment]
Same issue here. After deleting the config folder the error is still there.

**Comment by jaymoulin** [comment]
**/!\ Important**

Please fill the REQUIRED document when you open an issue so the debug could be processed - it asks for mandatory information 

----

As you may notice I am away from Github for days, months, years so, the more information you give, the easier it will to fix any issue.

Note that if you want more support, you may participate in supporting me 
[![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin)
[![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/jaymoulin)
[![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin)

---

If you can't wait for a fix to be made, you can also block the image update by using a previous version (probably 1.4.3 for instance as 2.0.0 brings a BC Break (cf. https://github.com/jaymoulin/docker-jdownloader/releases/tag/2.0.0))

example
```yml
services:
   jdownloader:
    image: jaymoulin/jdownloader:1.4.3
...
```

**Comment by karl0ss** [comment]
@jaymoulin just to confirm, I have reverted to the said version, and even with a clean install the same happens, it seems to be after an upstream update of JD happens inside the container...

**Comment by jaymoulin** [comment]
Well if it's related to the behaviour of JDownloader, this is not related to the Docker image, there, not related to this repo. You may ask further information on the [JDownloader official support](https://support.jdownloader.org/).

**Comment by thawn** [comment]
I ran into the same issue today after adding
user: 1000:100
to the compose.yml file
without the user it works.

Would it be possible to adapt the docker file to set the correct permissions upon start?
I guess the easiest would be to chown -R the entire jdownloader directory.

**Comment by jaymoulin** [comment]
@thawn I confirm the user issue was fixed (https://github.com/jaymoulin/docker-jdownloader/commit/142f137c8f8260db6a910fa40c1038fb882973c3). Please update your configuration and check everything is conform to instructions. If problem persists, create a new issue with all required informations.
