### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by karl0ss** [jaymoulin/docker-jdownloader#104]
I rolled back versions on my linux box, even wiped all folders and started fresh, still the same issue, I have now tried spinning it up on my windows box, using your commands from the readme, and it still dies.

---

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
2.0.1-amd64
```

**Description**
After the container spins up, JD does an update, then never starts or works, have also tried manaully setting the user/pass using `docker exec jdownloader configure email@email.com password` but restarts to the same issue.

**Command line I used to start the container**
`docker run -d --init --restart=always -v C:\\Users\\karl.hudgell\\myjd\\down:/opt/JDownloader/Downloads -v C:\\Users\\karl.hudgell\\myjd\\conf:/opt/JDownloader/app/cfg --name jdownloader -u $(id -u) -p 3129:3129 -e MYJD_USER=myusername -e MYJD_PASSWORD=mypassword -e MYJD_DEVICE_NAME=goofy jaymoulin/jdownloader`

**Steps to reproduce the issue:**
Start the container

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> CFG File does not exist: /opt/JDownloader/app/cfg/jd.controlling.faviconcontroller.FavIconsConfig.json
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> CFG File does not exist: /opt/JDownloader/app/cfg/org.jdownloader.settings.SoundSettings.json
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> CFG File does not exist: /opt/JDownloader/app/cfg/org.jdownloader.gui.notify.gui.BubbleNotifyConfig.json
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> CFG File does not exist: /opt/JDownloader/app/cfg/jd.controlling.captcha.CaptchaSettings.json
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /captcha = interface org.jdownloader.api.captcha.CaptchaAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /captchaforward = interface org.jdownloader.captcha.api.CaptchaForwarderAPIInterface
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /jd = interface org.jdownloader.api.jd.JDAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /downloads = interface org.jdownloader.api.downloads.DownloadsAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /downloadsV2 = interface org.jdownloader.api.downloads.v2.DownloadsAPIV2
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /downloadcontroller = interface org.jdownloader.api.downloads.v2.DownloadWatchdogAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /config = interface org.jdownloader.api.config.AdvancedConfigManagerAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /toolbar = interface org.jdownloader.api.toolbar.JDownloaderToolBarAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /accounts = interface org.jdownloader.api.accounts.AccountAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /accountsV2 = interface org.jdownloader.api.accounts.v2.AccountAPIV2
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /system = interface org.jdownloader.api.system.SystemAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /linkcollector = interface org.jdownloader.api.linkcollector.LinkCollectorAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /linkgrabberv2 = interface org.jdownloader.api.linkcollector.v2.LinkCollectorAPIV2
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /content = interface org.jdownloader.api.content.ContentAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /contentV2 = interface org.jdownloader.api.content.v2.ContentAPIV2
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /ui = interface org.jdownloader.api.ui.UIAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /polling = interface org.jdownloader.api.polling.PollingAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /extraction = interface org.jdownloader.api.extraction.ExtractionAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /linkcrawler = interface org.jdownloader.api.linkcrawler.LinkCrawlerAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /plugins = interface org.jdownloader.api.plugins.PluginsAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace / = interface org.jdownloader.api.cnl2.Cnl2APIBasics
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /flash = interface org.jdownloader.api.cnl2.Cnl2APIFlash
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /downloadevents = interface org.jdownloader.api.downloads.DownloadControllerEventPublisherInterface
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /extensions = interface org.jdownloader.api.extensions.ExtensionsAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /update = interface org.jdownloader.api.update.UpdateAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /device = interface org.jdownloader.api.device.DeviceAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /reconnect = interface org.jdownloader.api.reconnect.ReconnectAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /log = interface org.jdownloader.api.logs.LogAPI
26|Log.L.log 12/7/21 9:43:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /dialogs = interface org.jdownloader.api.dialog.DialogApiInterface
26|Log.L.log 12/7/21 9:43:41 AM - SEVERE [ Log.L.log ] -> Exception thrown at jd.SecondLevelLaunch$9$1.run(SecondLevelLaunch.java:919):
java.lang.ExceptionInInitializerError
        at jd.SecondLevelLaunch$9$1.run(SecondLevelLaunch.java:747)
Caused by: java.lang.RuntimeException: No Console Available!
        at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
        at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
        at org.jdownloader.api.myjdownloader.MyJDownloaderController.askLoginsOnConsole(MyJDownloaderController.java:273)
        at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:125)
        at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:112)
        at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:37)
        ... 1 more

</pre>
</details>

**Comment by jaymoulin** [comment]
Provided logs does not indicate any error. Please check your credentials.
