### ISSUE TITLE
Can't connect to the server using MyJDowloader

### ISSUE THREAD

**Issue by danfercf1** [jaymoulin/docker-jdownloader#106]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
2.0.2-armhf
```

**Description**

I can't connect to the server, I sign in into the https://my.jdownloader.org/index.html page but my JDownloader server does not showed here, I tried to configure the MyJD access in a normal JDownloader installed in a Windows installation and it is working well, the server is showed in the page.

There is another thing, but I think that is not related to this issue, in the logs I have a warning regarding the -norestart parameter
```
StartupParameterHandler.log 12/27/21, 1:06:46 PM - WARNING [ org.jdownloader.startup.ParameterHandler(execute) ] -> Invalid Command: norestart - []
```

**Command line I used to start the container**

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
INFO >> sun.Desktop: null
INFO >> XDG_CURRENT_DESKTOP: null
INFO >> KDE_FULL_SESSION: null
INFO >> KDE_SESSION_VERSION: null
INFO >> DESKTOP_SESSION: null
INFO >> GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/app/cfg/org.appwork.utils.logging2.LogConfig.json
SystemEntropyWorkaround:false
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory|Mode:NORMAL
Multiple LogControllers Detected: org.jdownloader.logging.LogController|org.jdownloader.logging.LogController@1dc8ecb
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
UpdateClient Proxy Vole 1
Update Message: Check for updates
Update Message: New JDownloader Version found...
Update Progress: 5%
Update Message: Prepare Update package...
Update Progress: -1%
Update Progress: 5%
Update Message: Prepare Update package...
Update Message: Download Updates...
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.225%
Update Message: Download Updates...
Downloadspeed: 0 B/s, Time left: 00s
Update Progress: 10.295%
Update Message: Download Updates...
Update Progress: 11.54%
Update Message: Download Updates...
Downloadspeed: 509.57 KB/s, Time left: 01m:23s
Update Progress: 13.041%
Update Message: Download Updates...
Downloadspeed: 1.11 MB/s, Time left: 45s
Update Progress: 14.408%
Update Message: Download Updates...
Downloadspeed: 1.13 MB/s, Time left: 43s
Update Progress: 15.362%
Update Message: Download Updates...
Downloadspeed: 1.12 MB/s, Time left: 42s
Update Progress: 16.98%
Update Message: Download Updates...
Downloadspeed: 1.05 MB/s, Time left: 46s
Update Progress: 18.485%
Update Message: Download Updates...
Downloadspeed: 1.05 MB/s, Time left: 45s
Update Progress: 20.071%
Update Message: Download Updates...
Downloadspeed: 1.05 MB/s, Time left: 45s
Update Progress: 21.577%
Update Message: Download Updates...
Downloadspeed: 1.05 MB/s, Time left: 45s
Update Progress: 23.105%
Update Message: Download Updates...
Downloadspeed: 1.03 MB/s, Time left: 45s
Update Progress: 24.727%
Update Message: Download Updates...
Downloadspeed: 1.02 MB/s, Time left: 44s
Update Progress: 26.267%
Update Message: Download Updates...
Downloadspeed: 1.03 MB/s, Time left: 44s
Update Progress: 27.998%
Update Message: Download Updates...
Downloadspeed: 1.02 MB/s, Time left: 44s
Update Progress: 29.48%
Update Message: Download Updates...
Downloadspeed: 1.02 MB/s, Time left: 44s
Update Progress: 29.733%
Update Message: Download Updates...
Downloadspeed: 1.01 MB/s, Time left: 43s
Update Progress: 29.968%
Update Message: Download Updates...
Downloadspeed: 1.00 MB/s, Time left: 43s
Update Progress: 30.107%
Update Message: Download Updates...
Downloadspeed: 1.00 MB/s, Time left: 42s
Update Progress: 30.155%
Update Message: Download Updates...
Downloadspeed: 968.58 KB/s, Time left: 46s
Update Progress: 30.757%
Update Message: Download Updates...
Downloadspeed: 1023.41 KB/s, Time left: 40s
Update Progress: 31.056%
Update Message: Download Updates...
Downloadspeed: 1.00 MB/s, Time left: 39s
Update Progress: 31.321%
Update Message: Download Updates...
Downloadspeed: 1.00 MB/s, Time left: 38s
Update Progress: 31.679%
Update Message: Download Updates...
Downloadspeed: 1.01 MB/s, Time left: 36s
Update Progress: 32.093%
Update Message: Download Updates...
Downloadspeed: 1.03 MB/s, Time left: 34s
Update Progress: 32.606%
Update Message: Download Updates...
Downloadspeed: 1.06 MB/s, Time left: 31s
Update Progress: 32.906%
Update Message: Download Updates...
Downloadspeed: 1.07 MB/s, Time left: 29s
Update Progress: 33.411%
Update Message: Download Updates...
Downloadspeed: 1.08 MB/s, Time left: 27s
Update Progress: 33.874%
Update Message: Download Updates...
Downloadspeed: 1.09 MB/s, Time left: 25s
Update Progress: 34.421%
Update Message: Download Updates...
Downloadspeed: 1.12 MB/s, Time left: 23s
Update Progress: 34.849%
Update Message: Download Updates...
Downloadspeed: 1.13 MB/s, Time left: 21s
Update Progress: 35.222%
Update Message: Download Updates...
Downloadspeed: 1.13 MB/s, Time left: 20s
Update Progress: 35.731%
Update Message: Download Updates...
Downloadspeed: 1.15 MB/s, Time left: 18s
Update Progress: 35.984%
Update Message: Download Updates...
Downloadspeed: 1.14 MB/s, Time left: 17s
Update Progress: 36.488%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 15s
Update Progress: 36.769%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 14s
Update Progress: 37.196%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 13s
Update Progress: 37.463%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 12s
Update Progress: 37.645%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 12s
Update Progress: 37.645%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 12s
Update Progress: 37.645%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 12s
Update Progress: 37.645%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 12s
Update Progress: 37.645%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 12s
Update Progress: 37.694%
Update Message: Download Updates...
Downloadspeed: 1.05 MB/s, Time left: 13s
Update Progress: 39.66%
Update Message: Download Updates...
Downloadspeed: 1.15 MB/s, Time left: 06s
Update Progress: 39.936%
Update Message: Download Updates...
Downloadspeed: 1.15 MB/s, Time left: 05s
Update Progress: 40.374%
Update Message: Download Updates...
Downloadspeed: 1.15 MB/s, Time left: 03s
Update Progress: 40.724%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 02s
Update Progress: 41.076%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 01s
Update Progress: 41.487%
Update Message: Download Updates...
Downloadspeed: 1.16 MB/s, Time left: 00s
Update Message: New Update available
Update Message: Extracting Updatepackage - please wait...
Update Progress: 41.646%
Update Progress: 41.646%
Update Progress: 42.446%
Update Progress: 44.712%
Update Progress: 46.978%
Update Progress: 49.377%
Update Progress: 50.43%
Update Progress: 50.584%
Update Progress: 50.755%
Update Progress: 50.908%
Update Progress: 51.071%
Update Progress: 51.259%
Update Progress: 51.575%
Update Progress: 51.805%
Update Progress: 52.087%
Update Progress: 52.404%
Update Progress: 52.634%
Update Progress: 52.805%
Update Progress: 52.993%
Update Progress: 53.104%
Update Progress: 53.309%
Update Progress: 53.472%
Update Progress: 53.66%
Update Progress: 53.856%
Update Progress: 54.044%
Update Progress: 54.223%
Update Progress: 54.386%
Update Progress: 54.548%
Update Progress: 54.727%
Update Progress: 54.907%
Update Progress: 55.078%
Update Progress: 55.283%
Update Progress: 55.471%
Update Progress: 55.821%
Update Progress: 56.18%
Update Progress: 56.539%
Update Progress: 56.915%
Update Progress: 57.282%
Update Progress: 57.641%
Update Progress: 58.034%
Update Progress: 58.359%
Update Progress: 58.76%
Update Progress: 58.76%
Update Progress: 58.76%
Update Progress: 58.76%
Update Progress: 58.76%
Update Progress: 58.965%
Update Progress: 59.369%
Update Message: Installation in progress - please wait...
Update Progress: 81.716%
Update Message: Installation in progress - please wait...
Update Message: Validating Installation.
This can take up to 5 minutes...
Update Progress: -1%
INFO >> sun.Desktop: null
INFO >> XDG_CURRENT_DESKTOP: null
INFO >> KDE_FULL_SESSION: null
INFO >> KDE_SESSION_VERSION: null
INFO >> DESKTOP_SESSION: null
INFO >> GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/app/cfg/org.appwork.utils.logging2.LogConfig.json
SystemEntropyWorkaround:false
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory|Mode:NORMAL
Multiple LogControllers Detected: org.jdownloader.logging.LogController|org.jdownloader.logging.LogController@1dc8ecb
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
UpdateClient Proxy Vole 1
Update Message: Check for updates
Update Progress: 0%
Update Progress: 7.448%
Update Progress: 10%
Update Message: Installation in progress - please wait...
Update Progress: 10.054%
Update Message: Installation in progress - please wait...
Update Progress: 16.203%
Update Message: Installation in progress - please wait...
Update Progress: 16.203%
Update Message: Installation in progress - please wait...
Update Progress: 25.412%
Update Message: Installation in progress - please wait...
Update Progress: 31.298%
Update Message: Installation in progress - please wait...
Update Progress: 35.309%
Update Message: Installation in progress - please wait...
Update Progress: 36.51%
Update Message: Installation in progress - please wait...
Update Progress: 36.751%
Update Message: Installation in progress - please wait...
Update Progress: 38.508%
Update Message: Installation in progress - please wait...
Update Progress: 38.857%
Update Message: Installation in progress - please wait...
Update Progress: 39.191%
Update Message: Installation in progress - please wait...
Update Progress: 39.503%
Update Message: Installation in progress - please wait...
Update Progress: 39.842%
Update Message: Installation in progress - please wait...
Update Progress: 39.942%
Update Message: Installation in progress - please wait...
Update Progress: 40.207%
Update Message: Installation in progress - please wait...
Update Progress: 40.518%
Update Message: Installation in progress - please wait...
Update Progress: 40.702%
Update Message: Installation in progress - please wait...
Update Progress: 40.702%
Update Message: Installation in progress - please wait...
Update Progress: 40.705%
Update Message: Installation in progress - please wait...
Update Progress: 40.705%
Update Message: Installation in progress - please wait...
Update Progress: 40.705%
Update Message: Installation in progress - please wait...
Update Progress: 41.131%
Update Message: Installation in progress - please wait...
Update Progress: 41.515%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 41.843%
Update Message: Installation in progress - please wait...
Update Progress: 42.077%
Update Message: Installation in progress - please wait...
Update Progress: 42.425%
Update Message: Installation in progress - please wait...
Update Progress: 42.731%
Update Message: Installation in progress - please wait...
Update Progress: 43.111%
Update Message: Installation in progress - please wait...
Update Progress: 43.632%
Update Message: Installation in progress - please wait...
Update Progress: 44.046%
Update Message: Installation in progress - please wait...
Update Progress: 44.525%
Update Message: Installation in progress - please wait...
Update Progress: 44.891%
Update Message: Installation in progress - please wait...
Update Progress: 45.325%
Update Message: Installation in progress - please wait...
Update Progress: 45.72%
Update Message: Installation in progress - please wait...
Update Progress: 46.21%
Update Message: Installation in progress - please wait...
Update Progress: 46.634%
Update Message: Installation in progress - please wait...
Update Progress: 47.067%
Update Message: Installation in progress - please wait...
Update Progress: 47.39%
Update Message: Installation in progress - please wait...
Update Progress: 47.546%
Update Message: Installation in progress - please wait...
Update Progress: 47.92%
Update Message: Installation in progress - please wait...
Update Progress: 48.377%
Update Message: Installation in progress - please wait...
Update Progress: 48.929%
Update Message: Installation in progress - please wait...
Update Progress: 49.27%
Update Message: Installation in progress - please wait...
Update Progress: 49.449%
Update Message: Installation in progress - please wait...
Update Progress: 49.91%
Update Message: Installation in progress - please wait...
Update Progress: 50.183%
Update Message: Installation in progress - please wait...
Update Progress: 50.183%
Update Message: Installation in progress - please wait...
Update Progress: 50.452%
Update Message: Installation in progress - please wait...
Update Progress: 50.452%
Update Message: Installation in progress - please wait...
Update Progress: 50.452%
Update Message: Installation in progress - please wait...
Update Progress: 50.452%
Update Message: Installation in progress - please wait...
Update Progress: 50.452%
Update Message: Installation in progress - please wait...
Update Progress: 50.814%
Update Message: Installation in progress - please wait...
Update Progress: 51.243%
Update Message: Installation in progress - please wait...
Update Progress: 51.826%
Update Message: Installation in progress - please wait...
Update Progress: 52.124%
Update Message: Installation in progress - please wait...
Update Progress: 53.061%
Update Message: Installation in progress - please wait...
Update Progress: 53.665%
Update Message: Installation in progress - please wait...
Update Progress: 53.88%
Update Message: Installation in progress - please wait...
Update Progress: 53.895%
Update Message: Installation in progress - please wait...
Update Progress: 53.895%
Update Message: Installation in progress - please wait...
Update Progress: 53.895%
Update Message: Installation in progress - please wait...
Update Progress: 53.895%
Update Message: Installation in progress - please wait...
Update Progress: 53.895%
Update Message: Installation in progress - please wait...
Update Progress: 53.952%
Update Message: Installation in progress - please wait...
Update Progress: 54.143%
Update Message: Installation in progress - please wait...
Update Progress: 55.251%
Update Message: Installation in progress - please wait...
Update Progress: 57.178%
Update Message: Installation in progress - please wait...
Update Progress: 57.731%
Update Message: Installation in progress - please wait...
Update Progress: 58.182%
Update Message: Installation in progress - please wait...
Update Progress: 58.41%
Update Message: Installation in progress - please wait...
Update Progress: 58.556%
Update Message: Installation in progress - please wait...
Update Progress: 58.775%
Update Message: Installation in progress - please wait...
Update Progress: 58.938%
Update Message: Installation in progress - please wait...
Update Progress: 59.117%
Update Message: Installation in progress - please wait...
Update Progress: 59.117%
Update Message: Installation in progress - please wait...
Update Progress: 59.117%
Update Message: Installation in progress - please wait...
Update Progress: 59.147%
Update Message: Installation in progress - please wait...
Update Progress: 59.147%
Update Message: Installation in progress - please wait...
Update Progress: 59.147%
Update Message: Installation in progress - please wait...
Update Progress: 59.147%
Update Message: Installation in progress - please wait...
Update Progress: 59.147%
Update Message: Installation in progress - please wait...
Update Progress: 59.158%
Update Message: Installation in progress - please wait...
Update Progress: 59.163%
Update Message: Installation in progress - please wait...
Update Progress: 59.209%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.234%
Update Message: Installation in progress - please wait...
Update Progress: 59.571%
Update Message: Installation in progress - please wait...
Update Progress: 61.131%
Update Message: Installation in progress - please wait...
Update Progress: 63.497%
Update Message: Installation in progress - please wait...
Update Progress: 66.028%
Update Message: Installation in progress - please wait...
Update Progress: 68.578%
Update Message: Installation in progress - please wait...
Update Progress: 68.968%
Update Message: Installation in progress - please wait...
Update Progress: 68.968%
Update Message: Installation in progress - please wait...
Update Progress: 68.968%
Update Message: Installation in progress - please wait...
Update Progress: 69.598%
Update Message: Installation in progress - please wait...
Update Progress: 71.961%
Update Message: Installation in progress - please wait...
Update Progress: 72.873%
Update Message: Installation in progress - please wait...
Update Progress: 75.379%
Update Message: Installation in progress - please wait...
Update Progress: 77.85%
Update Message: Installation in progress - please wait...
Update Progress: 80.736%
Update Message: Installation in progress - please wait...
Update Progress: 83.959%
Update Message: Installation in progress - please wait...
Update Progress: 87.566%
Update Message: Installation in progress - please wait...
Update Progress: 91.379%
Update Message: Installation in progress - please wait...
Update Progress: 97.867%
Update Message: Installation in progress - please wait...
Update Progress: 100%
Update Message: Finalizing installation...
Update Progress: 100%
Update Message: Finalizing installation...
Update Progress: 100%
Update Message: Finalizing installation...
SevenZipJBinding: null
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/Core.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/Dynamics.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/Filters.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JAntiCaptcha.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JDGUI.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JDHttp.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/JDUtils.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/cling-core.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/cling-support.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/seamless-http.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/seamless-util.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/UPNP/seamless-xml.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/bcpkix-jdk15on.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/bcprov-jdk15on.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/bctls-jdk15on.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/brotli.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/cons.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/debug-disable.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/hexdump.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/libdbus-java.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/dbus/unix.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/htmlunit-core-js.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/image4j.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jackson-annotations.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jackson-core.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jackson-databind.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jna.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jna_platform.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/js.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/jsyntaxpane.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/laf/synthetica.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/laf/syntheticaJDCustom.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/laf/syntheticaSimple2D.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/proxyVole.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/sevenzipjbinding.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/sevenzipjbindingLinuxArmVersion.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/svgSalamander.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/libs/zip4j.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/extensions/Extraction.jar
Add via JDLauncherClassLoader.addURL:file:/opt/JDownloader/app/extensions/JDShutdown.jar
Cryptography restrictions removal not needed
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
Update Message: Check for updates
Update Progress: 100%
</pre>
</details>

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

To connect your instance you must follow [the identify instructions](https://github.com/jaymoulin/docker-jdownloader#identify)
