### ISSUE TITLE
Issues with image on raspberry pi

### ISSUE THREAD

**Issue by phampyk** [jaymoulin/docker-jdownloader#107]
Hello, I've seen come closed issues with the same problem as mine, but I've been working around it, and first of all I changed the daemon.sh so the "java -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -jar /opt/JDownloader/JDownloader.jar -norestart" doesn't have an & at the end, That stops it from giving the error of "no console available"
Then I did a "docker attach jdownloader" because jdownloader was asking me for my credentials, even tho they were on the env as per instructions. Even tried the "docker exec jdownloader configure email@email.com password" but it didn't work either. 
In the end I had to do it manually though docker attach, and added my email and pass, now it's working but the name of the JD is not the one on the env either.
I think the problem is that Jdownloader is not accessing the env variables added to the container.
Not sure if you need any more information, just wanted to let you know, and maybe this could be helpful for someone else

**Comment by jaymoulin** [comment]
Thank you for using this repository. As you may know, maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

Here are many reason I close this thread:
- You ignored the issue template, which I took time to redact, preventing me, and all other users, to know the context of your issue, resulting in an unreproduceable issue
- You forked the application and added multiple code modification, altering the original behaviour
- Your "issue" does not bring any information nor question
