### ISSUE TITLE
decoding and naming files

### ISSUE THREAD

**Issue by CeskoFTB** [jaymoulin/docker-jdownloader#109]
After a download from 'Mega' the file should be named coorectly but instead the decoding of the file is done but without renaming and a file is persisting.

The 'cbr' file is working but the name isn't the good one and even the characters are weard (capital and special characters) as described in the screenshots below.

The expected name should be "le labyrinthe - la terre brûlée.cbr" and not "LKZX8W~7.CBR"

I tried to download again, it does that every time. 

EDIT : I switched to "https://github.com/antlafarge/jdownloader" and everything works like a charm with any links in any languages...

![Screenshot_2022-01-27-12-58-27-658_org appwork myjdandroid](https://user-images.githubusercontent.com/97540714/151355333-b1f2f89d-d37e-45ba-9209-71f5f7dc18df.jpg)
![Screenshot_2022-01-27-13-00-27-171_com cxinventor file explorer](https://user-images.githubusercontent.com/97540714/151355341-901b8c5d-b192-4dc4-a8bb-58df58162d04.jpg)

**Comment by jaymoulin** [comment]
Not enough information to handle this issue. without information, the issue will be closed+locked

**Comment by CeskoFTB** [comment]
I switched to "https://github.com/antlafarge/jdownloader" and everything works like a charm with any links in any languages
