### ISSUE TITLE
Folder dl

### ISSUE THREAD

**Issue by Lunqtic** [jaymoulin/docker-jdownloader#11]
Hello,

It's possible to change the folder download to NAS ? 

I use Rpi2.

Thx.

**Comment by jaymoulin** [comment]
All the magic is in the settings and your launch command.

with the ` -v ~/Downloads:/root/Downloads` parameter, you tell docker that you want the folder `/root/Downloads` of your docker container (jdownloader application) to be mounted as a volume with the Download folder in your home directory (~/Downloads). You can either change the `~/Downloads` path to the folder you want or change in `MyJdownload > Settings > Default Download Folder` to change in your docker container.

In the last case, you will have to mount a volume to the desired path.
https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag
