### ISSUE TITLE
Invalid Download Directory

### ISSUE THREAD

**Issue by dnl0319** [jaymoulin/docker-jdownloader#113]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
pi@NAS:~ $ docker inspect jdownloader --format='{{index .Config.Labels.version}}'

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/jdownloader/json": dial unix /var/run/docker.sock: connect: permission denied
```

**Description**
I was tring to download something but I get the replay "invalid Download Directory"

I have to say I needed to modify the path /opt/JDownloader/app/cfg to /opt/JDownloader/cfg, because otherwise I couldn't get jdownloader running. I saw that path on older how to youtube videos obout docker and jdownloader so I tried and it worked.

I have to say I usw OMV with Docker and Portainer.

**Command line I used to start the container**
services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: 1001:100
    volumes:
        - /srv/dev-disk-by-uuid-5523fbfa-7dd4-4a74-8fa7-31feb1cf4919/appdata/jdownloader:/opt/JDownloader/cfg
        - /srv/dev-disk-by-uuid-5523fbfa-7dd4-4a74-8fa7-31feb1cf4919/downloads/jdownloader:/opt/JDownloader/Downloads
        - /etc/localtime:/etc/localtime:ro #optional
    environment: 
            MYJD_USER: xxx@xx.de #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_PASSWORD: 123456 #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: NAS #optional
    ports:
        - 3129:3129

**Steps to reproduce the issue:**
1. import the stacks in portainer
2. deploy
3. and try to download something

**Describe the results you received:**
Invalid Download Directory is displayed in the Webif of MYJD when I try to download something

**Describe the results you expected:**

That I can download something.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
pi@NAS:~ $ docker logs jdownloader
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/jdownloader/json": dial unix /var/run/docker.sock: connect: permission denied
</pre>
</details>

**Comment by jaymoulin** [comment]
[](https://www.paypal.me/jaymoulin)[](https://www.buymeacoffee.com/3Yu8ajd7W)[](https://patreon.com/jaymoulin)Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms PayPal donation Buy me a coffee Become a Patron.

Your command line does not seems to match the way you started your container. Dont follow the video you watched, follow the README instructions. The path given in it are the actual ones that are needed to work.

The error you got is clear of what you have to to to fix your issue:

```Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/jdownloader/json": dial unix /var/run/docker.sock: connect: permission denied```

The user used to launch the container does not have rights to launch any docker container. You must give your user the docker rights (usermod -aG docker $USER)
