### ISSUE TITLE
no JAR command 

### ISSUE THREAD

**Issue by xgoos** [jaymoulin/docker-jdownloader#123]
Hello Jay.
   Thank you so much for your great work. With my knowlage about containers I am not able to say why it's possible. But in my instance of your docker image there is no JAR command. That's why the condition in deamon.sh on line 37 works not as it's designed and file is deleted. File /opt/JDownloader/app/tmp/update/self/JDU/JDownloader.jar doesn't exists. That's why /opt/JDownloader/app/JDownloader.jar can't be executed at the end of the script. 

My OS where I'am Docker running:
   NAME="LibreELEC"
   VERSION="10.0.3"
   ID="libreelec"
   VERSION_ID="10.0"
   PRETTY_NAME="LibreELEC (official): 10.0.3"
   HOME_URL="https://libreelec.tv"
   BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
   BUILD_ID="c73c0302e412a655d1da320dcd440c011f599cb7"
   LIBREELEC_ARCH="RPi4.arm"
   LIBREELEC_BUILD="official"
   LIBREELEC_PROJECT="RPi"
   LIBREELEC_DEVICE="RPi4"

My Docker version:
   Docker version 19.03.15, build 99e3ed89195c4e551e87aad1e7453b65456b03ad

Thank you
David

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/jaymoulin) [![Buy me a coffee](https://ko-fi.com/img/githubbutton_sm.svg "Buy me a coffee")](https://www.ko-fi.com/jaymoulin).

As you decided to remove all my issue template, you're not giving me mandatory information so I can help you.
This said, it's likely you mounted a volume in an incorrect path or using a wrong image architecture

**Comment by xgoos** [comment]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
2.1.0-armel
```

**Description**



**Command line I used to start the container**
docker run -d --init --restart=unless-stopped -v /storage/downloads/JDownloader:/opt/JDownloader/Downloads -v /storage/backup/JDownloader/cfg:/opt/JDownloader/app/cfg -v /storage/backup/JDownloader/logs:/opt/JDownloader/app/logs --name jdownloader -u $(id -u) -p 3129:3129 -e MYJD_USER=XXXX@XXX.XXX -e MYJD_PASSWORD=XXXXXXX -e MYJD_DEVICE_NAME=Raspberry jaymoulin/jdownloader

**Steps to reproduce the issue:**
1. docker run ....

**Describe the results you received:**
ID of container

**Describe the results you expected:**
ID of container

**Additional information you deem important (e.g. issue happens only occasionally):**
My OS where I'am Docker running:
NAME="LibreELEC"
VERSION="10.0.3"
ID="libreelec"
VERSION_ID="10.0"
PRETTY_NAME="LibreELEC (official): 10.0.3"
HOME_URL="https://libreelec.tv/"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="c73c0302e412a655d1da320dcd440c011f599cb7"
LIBREELEC_ARCH="RPi4.arm"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="RPi"
LIBREELEC_DEVICE="RPi4"

My Docker version:
Docker version 19.03.15, build 99e3ed89195c4e551e87aad1e7453b65456b03ad

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
/opt/JDownloader/daemon.sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: target '/opt/JDownloader/app/libs/' is not a directory
Error: Unable to access jarfile /opt/JDownloader/app/JDownloader.jar
</pre>
</details>
