### ISSUE TITLE
Got 3 IP address but which one is used for downloading?

### ISSUE THREAD

**Issue by seyo-IV** [jaymoulin/docker-jdownloader#126]
I have 3 IPS on my jd one from my local network, one from docker and one from VPN.

So how do I know what he uses for downloading? Or better how do I setup it that ways that he only uses the VPN one?

**Comment by seyo-IV** [comment]
ok i got something. When i use this command it shows tun0

ip route get 8.8.8.8 | sed -n 's/.*dev \([^\ ]*\).*/\1/p'

**Comment by jaymoulin** [comment]
This seems to be more of a Docker configuration than related to this repository
