### ISSUE TITLE
OPNsense + Unbound DNS settings for Direct Connections from LAN (NOT AN ISSUE)

### ISSUE THREAD

**Issue by FeRChImoNdE** [jaymoulin/docker-jdownloader#131]
Just want to share what I found as a working configuration in case of any of you using OPNsense + Unbound and want to take advantage of direct connections from LAN hosts.

### In OPNsense:

Services -> Unbound DNS -> Query Forwarding

- Domain: mydns.jdownloader.com
- IP Address: OPNsense's IP (e.g. 192.168.1.1)

Services -> Unbound DNS -> Advanced

- Private Domains:
mydns.jdownloader.com
*.mydns.jdownloader.com

### In jDownloader:

Settings -> Advanced Settings -> In the top search box search for MyJDownloaderSettings

- Custom Device IPs: ["jDownloader's Host IP"] <- be sure that the IP is enclosed by ["  "]  e.g. ["192.168.1.50"]
- Manual Local Port: As you want, e.g. 3129
- Manual Remote Port: As you want, e.g. 3129
- Direct Connect Mode: Allow lan/wan connections with manual port forwarding

Also if you forward that port in the Firewall NAT settings you can get (in theory) access from WAN interface, but I don't recommend doing that unless you know very well what are you doing.

**Comment by jaymoulin** [comment]
Thank you for those information, I'm sure it's useful for some people
