### ISSUE TITLE
PUID and GID are not working on Container Station QNAP NAS

### ISSUE THREAD

**Issue by isitLoVe** [jaymoulin/docker-jdownloader#135]
Thank you for implementing #133, however when setting those env the container does not start with the following message:
```
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
```

When the envs are removed the container works fine.

It looks like the PATH env variable is not working, maybe try addin -m or -p to the su command. Since i have limited docker support on the QNAP i cannot test it with a newly build container.

**Comment by jaymoulin** [comment]
I've made an issue template for a reason... With this, no one can do anything and the issue will just be ignored and closed

**Comment by isitLoVe** [comment]
Ok, sorry here is the input from the ISSUE template:

**Output of `docker inspect jdownloader --format='{{index.Config.Labels.version}}'`:**

```
[nasadmin@nas /]$ docker inspect jdownloader --format='{{index .Config.Labels.version}}'
2.2.0-linux/amd64
```

**Description**

Container does not start on QNAP NAS when using env GID and PUID.

**Command line I used to start the container**
Press start in the QNAP Container Station GUI

**Steps to reproduce the issue:**
1. Create a new container
2. Set env GID and PUID
3. Start the container

**Describe the results you received:**
Container does not start

**Describe the results you expected:**
Container should start and create downloaded files with the given chown & chgrp of the values in PUID and GID

**Additional information you deem important (e.g. issue happens only occasionally):**
QNAP TS-462
QTS 5.2.2.2950

Container Station
Version 3.0.9.1038 (2024/11/08)

Without PUID and GID the container is starting. (eg. not launched via su as stated in the entrypoint script)

**Provide some logs (`docker logs jdownloader`)**

sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
usermod: no changes
sh: java: not found
<details>
<pre>
(paste logs)
</pre>
</details>

**Comment by jaymoulin** [comment]
Latest version is 2.2.3. please check with this version and try again

**Comment by trohnjavolta** [comment]
Same issue for me, using dockstarter on debian server. I cannot pull version 2.2.3...I guess it just takes a while until it will be available?
