### ISSUE TITLE
Automatically restart after update without `--restart=always`

### ISSUE THREAD

**Issue by blackwind** [jaymoulin/docker-jdownloader#14]
Currently, this image needs to be run with `--restart=always` so it restarts after updating itself instead of just stopping. Alas, this method makes the [JD Shutdown](http://jdownloader.org/knowledge/wiki/addons/list/jdshutdown) extension useless, as the container will always happily start back up immediately after shutting down. Can you take a look at restarting JDownloader in-container after update instead of relying on Docker to do it unconditionally?

**Comment by jaymoulin** [comment]
The purpose of Docker is that container as to execute only on process. This is not a virtual machine and this feature won't fit with Docker purpose and/or recommandation. I suggest you fork my repo if you want to implements this feature
