### ISSUE TITLE
Can't get this to work on a Rock64 (with OMV on)

### ISSUE THREAD

**Issue by bonny1992** [jaymoulin/docker-jdownloader#15]
Hello! I'm trying to use your image (which looks fantastic, I have to admit) but I'm having troubles.
Not only the first boot of the container takes ages, but then when I try to see the installation on my.jdownloader it's not listed.

Have any tips to get this working? Thanks!

**Comment by jaymoulin** [comment]
Can you please give more information? (Version? logs?)

**Comment by bonny1992** [comment]
The version is actually the latest that docker pulls from the hub. Should I build the image instead?
Speaking of the logs instead it's quite difficult to get something relevant, it throws a lot of lines then writes "initialization finished" or something similar, then after 30/45 minutes goes with "checking update" and does nothing more. 
At the moment I don't have the device at hand, by the way. 

Do I have to open some ports? I haven't with the client on my windows machine.
Maybe this image isn't designed to run headlessly?

**Comment by jaymoulin** [comment]
By version, I mean, what is the return of this command : `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`

The purpose of this image IS to run headlessly. 
Did you configure your account (as specified in README)?
You don't have to open any port.
The more information you can give, the better I can resolve this issue.

**Comment by bonny1992** [comment]
Sorry about the closure, I'm on mobile and wrongfully tapped on the button.

Oh, as soon as I can get near the device then I'll get the version. 

Yes, I followed the README and if I look at the config files the account is configured.

**Comment by jaymoulin** [comment]
No problem, take your time ;)

**Comment by bonny1992** [comment]
Thank you!

Here's what the inspect command returns:

    > docker inspect jdownloader --format='{{index .Config.Labels.version}}'
    0.6.0

**Comment by jaymoulin** [comment]
Can you please try with version 0.5.0? This is not a sustainable solution but this will help debug (as I don't have a Rock64 myself). Also, can you please check that your device has enough free memory/CPU to be able to run OMV along with docker/jdownloader?

**Comment by bonny1992** [comment]
What command I need to run? Does 
    docker run -d <commands> jaymoulin/jdownloader:0.5.0
work?

Also yes, it should have plenty of memory and CPU.

**Comment by jaymoulin** [comment]
To be easier, you should delete your actual container and do the exact same process but using the `jaymoulin/jdownloader:0.5.0` image. That means you'll have to do the auth process again

**Comment by bonny1992** [comment]
> To be easier, you should delete your actual container and do the exact same process but using the `jaymoulin/jdownloader:0.5.0` image. That means you'll have to do the auth process again

Yep, I just didn't see the tags!
How much time I should wait before I report to you? Because right now the 0.5.0 tag isn't working either.

**Comment by jaymoulin** [comment]
Usually, when updates finishes, you just have to restart the container for the program to start normally.

**Comment by bonny1992** [comment]
Just restarted the container:

> 24|Log.L.log 10/21/18 7:32:08 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /log = interface org.jdownloader.api.logs.LogAPI
> 24|Log.L.log 10/21/18 7:32:08 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /dialogs = interface org.jdownloader.api.dialog.DialogApiInterface
> 24|Log.L.log 10/21/18 7:32:08 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.deviceconnectports.json
> 
> THREAD: 35
> 35|Log.L.log 10/21/18 7:32:08 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace / = interface org.jdownloader.api.cnl2.Cnl2APIBasics
> 35|Log.L.log 10/21/18 7:32:08 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /flash = interface org.jdownloader.api.cnl2.Cnl2APIFlash
> 
> THREAD: 37
> 37|Log.L.log 10/21/18 7:32:08 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/cfg/org.jdownloader.settings.AccountSettings.accounts.ejs
> 
> THREAD: 38
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> CFG File does not exist: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.jac.JACSolverConfig.json
> 
> THREAD: 24
> 24|Log.L.log 10/21/18 7:32:09 PM - INFO [ jd.controlling.DelayWriteController(init) ] -> DelayWriteMode: AUTO
> 24|Log.L.log 10/21/18 7:32:09 PM - INFO [ jd.controlling.DelayWriteController(init) ] -> DelayedWrites auto enabled because JDownloader is running in headless mode!
> 
> THREAD: 38
> 38|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.jac.JACSolverConfig|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.jac.JACSolverConfig
> 
> THREAD: 36
> 36|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.jdownloader.extensions.LazyExtension(getClassLoader) ] -> Use /opt/JDownloader/extensions/Extraction.jar classloader
> 
> THREAD: 38
> 38|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.jac.JACSolverConfig.jacthreshold.json
> 
> THREAD: 36
> 36|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.extensions.extraction.ExtractionExtension.json
> 36|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.extensions.extraction.ExtractionConfig|Path:/opt/JDownloader/cfg/org.jdownloader.extensions.extraction.ExtractionExtension
> 
> THREAD: 38
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.dbc.DeathByCaptchaSettings.json
> 38|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.dbc.DeathByCaptchaSettings|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.dbc.DeathByCaptchaSettings
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.dbc.DeathByCaptchaSettings.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.imagetyperz.ImageTyperzConfigInterface.json
> 38|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.imagetyperz.ImageTyperzConfigInterface|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.imagetyperz.ImageTyperzConfigInterface
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.imagetyperz.ImageTyperzConfigInterface.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.cheapcaptcha.CheapCaptchaConfigInterface.json
> 38|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.cheapcaptcha.CheapCaptchaConfigInterface|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.cheapcaptcha.CheapCaptchaConfigInterface
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.cheapcaptcha.CheapCaptchaConfigInterface.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.captchasolutions.CaptchaSolutionsConfigInterface.json
> 38|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.captchasolutions.CaptchaSolutionsConfigInterface|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.captchasolutions.CaptchaSolutionsConfigInterface
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.captchasolutions.CaptchaSolutionsConfigInterface.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 
> THREAD: 36
> 36|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Load Translation file:/opt/JDownloader/translations/org/jdownloader/extensions/extraction/translate/ExtractionTranslation.en.lng
> 
> THREAD: 38
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.twocaptcha.TwoCaptchaConfigInterface.json
> 38|Log.L.log 10/21/18 7:32:09 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.twocaptcha.TwoCaptchaConfigInterface|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.twocaptcha.TwoCaptchaConfigInterface
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.twocaptcha.TwoCaptchaConfigInterface.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 38|Log.L.log 10/21/18 7:32:09 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.antiCaptchaCom.AntiCaptchaComConfigInterface.json
> 38|Log.L.log 10/21/18 7:32:10 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.antiCaptchaCom.AntiCaptchaComConfigInterface|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.antiCaptchaCom.AntiCaptchaComConfigInterface
> 38|Log.L.log 10/21/18 7:32:10 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.antiCaptchaCom.AntiCaptchaComConfigInterface.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 38|Log.L.log 10/21/18 7:32:10 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.endcaptcha.EndCaptchaConfigInterface.json
> 38|Log.L.log 10/21/18 7:32:10 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.endcaptcha.EndCaptchaConfigInterface|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.endcaptcha.EndCaptchaConfigInterface
> 38|Log.L.log 10/21/18 7:32:10 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.endcaptcha.EndCaptchaConfigInterface.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 38|Log.L.log 10/21/18 7:32:10 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.solver9kw.Captcha9kwSettings.json
> 38|Log.L.log 10/21/18 7:32:10 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.captcha.v2.solver.solver9kw.Captcha9kwSettings|Path:/opt/JDownloader/cfg/org.jdownloader.captcha.v2.solver.solver9kw.Captcha9kwSettings
> 38|Log.L.log 10/21/18 7:32:10 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Overridden Config Key found public abstract boolean org.jdownloader.captcha.v2.solver.solver9kw.Captcha9kwSettings.isEnabled()<-->public abstract boolean org.jdownloader.captcha.v2.ChallengeSolverConfig.isEnabled()
> 
> THREAD: 36
> 36|Log.L.log 10/21/18 7:32:11 PM - INFO [ org.jdownloader.extensions.LazyExtension(getClassLoader) ] -> Use /opt/JDownloader/extensions/JDShutdown.jar classloader
> 36|Log.L.log 10/21/18 7:32:11 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.jdownloader.extensions.shutdown.ShutdownExtension.json
> 36|Log.L.log 10/21/18 7:32:11 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.extensions.shutdown.ShutdownConfig|Path:/opt/JDownloader/cfg/org.jdownloader.extensions.shutdown.ShutdownExtension
> 36|Log.L.log 10/21/18 7:32:11 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Load Translation file:/opt/JDownloader/translations/org/jdownloader/extensions/shutdown/translate/ShutdownTranslation.en.lng
> Start Update
> Update Message: Check for updates
> Update Progress: 3%
> Update Progress: -1%
> Update Message: Contact Server...
> Update Message: Check for updates
> Update Progress: 0%


I don't want to clog the thread with the logs, is there a file saved somewhere? So I can upload it!

**Comment by jaymoulin** [comment]
I updated your messages. Please use this syntax instead for robots to correctly index this page and users to keep following this topic.

**Comment by bonny1992** [comment]
Ok, no problem. Sorry about that!

So did you see the part of the logs? Is there anything helpful?

**Comment by jaymoulin** [comment]
May be related to #12 or #9. Can you please check your `docker version`?

**Comment by bonny1992** [comment]
Oh, didn't see those issues before.
Here's my docker version:

<details> 
<pre>
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:49 2018
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:55 2018
  OS/Arch:          linux/arm64
  Experimental:     false
</pre>
</details>

**Comment by jaymoulin** [comment]
I don't see any problem in your logs related to the docker image.

- Did you mount something to `/opt/JDownloader`?
- Did you launch container with a `-u` parameter?
- Can you please provide me with the logs you have between your container restarts? 
- What is the uptime of your jdownloader container (`docker ps -a`)?

**Comment by jaymoulin** [comment]
> Here's the original command I ran:
> 
> `docker run -d --name jdownloader --restart=unless-stopped -u -v /home/dw:/root/Downloads -v /home/jd/cfg:/opt/JDownloader/cfg jaymoulin/jdownloader`
> 
There is the problem. Don't use the `-u` parameter unless you pass it a correct value

> > Can you please provide me with the logs you have between your container restarts?
> 
> Is there any way to save the **entire** log to file?

`docker logs jdownloader > logs.txt`

**Comment by bonny1992** [comment]
> There is the problem. Don't use the -u parameter unless you pass it a correct value

Oh don't worry, in my tries I tried not using it, using it without parameters and using it with correct parameters (user:group, right?)

> `docker logs jdownloader > logs.txt`

Wouldn't it save even the old logs?

**Comment by jaymoulin** [comment]
> > There is the problem. Don't use the -u parameter unless you pass it a correct value
> 
> Oh don't worry, in my tries I tried not using it, using it without parameters and using it with correct parameters (user:group, right?)

Correct.

> 
> > `docker logs jdownloader > logs.txt`
> 
> Wouldn't it save even the old logs?

Only the logs for your container. If you delete it, it deletes the logs.

It's important to know what's going on between container restarts as jdownloader needs to restart to complete its update. If it fails, we'll probably see it in the logs. If not, then it's probably a jdownloader issue and I won't be able to help, nor the right repository for your issue

**Comment by bonny1992** [comment]
Ok, this is just when I created it:
[created.txt](https://github.com/jaymoulin/docker-jdownloader/files/2499689/logs.txt)

This just after the account command:
[account.txt](https://github.com/jaymoulin/docker-jdownloader/files/2499690/logs.txt)

I don't know when exactly one stops and begins the other, btw.

**Comment by jaymoulin** [comment]
Everything looks fine.
Please check your credentials are correct.
I can't help you any longer as it doesn't look like an image problem but if problem persists, I suggest you contact Jdownloader support so they can give you further information

**Comment by bonny1992** [comment]
I will shortly, can you tell me after how much time I should run the account login command?

Il 22 ott 2018 01:01, Jay MOULIN <notifications@github.com> ha scritto:

(Please use <details> instead of files for indexing purpose)

What do you mean by This just after the account command? Did you run several containers?

I can see many problems in those files:

  *   Your container seems to crash on updating process and restart. This is the most useful information here
  *   libs/sevenzipjbinding1509LinuxArm64.jar:false indicates false, which is not an expected value here as you're supposed to use an arm64 image.

Can you please:

  *   delete your actual container
  *   follow README.md instructions for container creation without the -u part and using the jaymoulin/jdownloader:0.6.0-arm64 image
  *   follow README.md instruction for account login in the same container
  *   restart your container

**Comment by bonny1992** [comment]
Ok I'm seeing progress!

I'm not near my rock64 right now but after some container deletions and a few reboots, yesterday night I have seen the instance appear on my jdownloader page!

As soon as I will be back home I'll check better!

**Comment by bonny1992** [comment]
I'm writing here after the closing of the issue to thank @jaymoulin because of his patience of guiding me to solving my problem!

Here's my instance finally stable, up and running!
![image](https://user-images.githubusercontent.com/1154368/47595962-5d0ee300-d983-11e8-90f2-0e25cce06c4d.png)

I don't sincerely know what fixed the issue, btw.
