### ISSUE TITLE
How to run as non-root user?

### ISSUE THREAD

**Issue by auanasgheps** [jaymoulin/docker-jdownloader#16]
**Description**
How to run as non-root user?
The following command is not clear for me
`-u $UID:$(id -g)`

My UID is 1029, GID is 100.
However you mention UID but the command `id -g` outputs GID.

Moreover, how do i check if jdwnloader is not running in root?
In logs from Portainer i see

1|org.jdownloader.update.launcher.SecondLevelLauncher.log 10/26/18 6:13:23 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: user.name: root

In a shell in the container, if I run `top` everything is running under root.

**Command line I used to start the container**
docker run -d \
--name=jdownloader \
--restart unless-stopped \
--net rete \
--ip 172.20.0.6 \
-v /volume1/docker/jdownloader/cfg:/opt/JDownloader/cfg \
-v /volume1/docker/jdownloader/logs:/opt/JDownloader/logs \
-v /volume/to/downloads:/downloads \
-v /etc/localtime:/etc/localtime:ro \
-u $UID:100 \
jaymoulin/jdownloader

I tried both $UID:100 and $UID:1029.

**Describe the results you received:**
Jdownloader running as root

**Describe the results you expected:**
Jdownloader running as UID 1029

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
(paste logs)
</pre>
</details>

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
0.6.0
```

**Comment by jaymoulin** [comment]
Just run with `-u 1029:100`. You device seems not to have defined `$UID` env variable

**Comment by auanasgheps** [comment]
Thanks, it's working!
