### ISSUE TITLE
Dont work in arm64 and libreelec

### ISSUE THREAD

**Issue by Sirfrancis17** [jaymoulin/docker-jdownloader#17]
Hello
I have installed this image as indicated in the manual in a system arm64
Ahe never been able to connect with Myjdownloader
Docker Container is running 
Attached the log

[log.txt](https://github.com/jaymoulin/docker-jdownloader/files/2524505/log.txt)
Thank you

**Comment by jaymoulin** [comment]
What do you mean by "Ahe never been able to connect with Myjdownloader"?
Did you execute the auth command? 

Why did you decide to provide logs without the information I need to resolve your problem as suggested in the issue template? (such as the version or the commands you typed). That would save a lot of time ;)

**Comment by Sirfrancis17** [comment]
Thanks for the help 
I have run the same tutorial commands
docker run -d --restart=always -v ~/Downloads:/root/Downloads -v ~/jdownloader/cfg:/opt/JDownloader/cfg --name jdownloader -u $UID:$(id -g) jaymoulin/jdownloader

docker exec jdownloader configure xxxxx@email.com xxxxxx

The container is working but I've also tried commands like 
Docker Start/Stop or restart jdownloader
Then I go to Myjdownloader. com but does not connect 
Am I missing a step?

**Comment by jaymoulin** [comment]
Can you please check that `echo $UID:$(id -g)` gives you something like `1039:100`?
Can you please check that your credentials are correct in the `~/jdownloader/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json` file?
What are the permissions of your folder `~/jdownloader/cfg/` folder?
What is the current status of your container and, if running, its uptime?
`docker logs -f --tail 2 jdownloader` should not be verbose with a running container doing nothing. Is it the case?

**Comment by Sirfrancis17** [comment]
> Can you please check that echo $UID:$(id -g) gives you something like 1039:100?

:0

> Can you please check that your credentials

{ 
  "autoconnectenabledv2" : true,
  "password" : "xxxxxx", CORRECT
  "email" : "xxxxxx@gmail.com" CORRECT
}

> What are the permissions of your folder ~/jdownloader/cfg/ folder?

drwxr-xr-x    2 root     root          4096 Oct 30 09:09

> What is the current status of your container and, if running, its uptime?

file attach
[log.txt](https://github.com/jaymoulin/docker-jdownloader/files/2528848/log.txt)

thanks for the help

**Comment by jaymoulin** [comment]
> > Can you please check that echo $UID:$(id -g) gives you something like 1039:100?
> 
> :0
Looks like you have a problem here. Please delete your container and don't use the `-u $UID:$(id -g)` par as your $UID / $GID seems not to be defined.
> 
> > Can you please check that your credentials
> 
> {
> "autoconnectenabledv2" : true,
> "password" : "xxxxxx", CORRECT
> "email" : "[xxxxxx@gmail.com](mailto:xxxxxx@gmail.com)" CORRECT
> }
> 
> > What are the permissions of your folder ~/jdownloader/cfg/ folder?
> 
> drwxr-xr-x 2 root root 4096 Oct 30 09:09
> 
> > What is the current status of your container and, if running, its uptime?
> 
> file attach
> [log.txt](https://github.com/jaymoulin/docker-jdownloader/files/2528848/log.txt)
>

I asked for your container status and uptime, not your logs. `docker ps -a | grep jdownloader`

> docker logs -f --tail 2 jdownloader should not be verbose with a running container doing nothing. Is it the case?

I'm not asking here for logs, I'm just asking if you see something speaking or being mute as this command won't return until you stop it.

**Comment by Sirfrancis17** [comment]
> Please delete your container and don't use the -u $UID:$(id -g) par as your $UID / $GID seems not to be defined.

do it and it doesn't work

> docker ps -a | grep jdownloader

0be0e7541d8f        jaymoulin/jdownloader   "tini -- /opt/JDow..."   2 minutes ago       Up 11 seconds                           jdownloader

> this command won't return until you stop it. 

the command stopped alone

`16|org.jdownloader.update.UpdateManager.log 10/30/18 9:27:38 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Running
16|org.jdownloader.update.UpdateManager.log 10/30/18 9:27:38 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> File exists
16|org.jdownloader.update.UpdateManager.log 10/30/18 9:27:40 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> Validate:  OK
16|org.jdownloader.update.UpdateManager.log 10/30/18 9:27:40 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> SelfTest Results:
OK
16|org.jdownloader.update.UpdateManager.log 10/30/18 9:27:40 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> OK
16|org.jdownloader.update.UpdateManager.log 10/30/18 9:27:40 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> Self Update successful
16|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> Request Shutdown: org.jdownloader.updatev2.SmartRlyExitRequest@1e58603
16|Log.L.log 10/30/18 9:27:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> No Vetos
16|Log.L.log 10/30/18 9:27:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Fire onShutDownEvents
16|Log.L.log 10/30/18 9:27:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Create ExitThread
16|Log.L.log 10/30/18 9:27:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Wait
THREAD: 22
22|Log.L.log 10/30/18 9:27:40 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Exit Now: Code: 0
THREAD: 8
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/7|Priority: 10000]ShutdownController: start item->ShutdownRunableEvent Priority: 10000
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/7|Priority: 10000]ShutdownController: item ended after->7
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:1/7]
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/7|Priority: 10000]ShutdownController: start item->flushing logs to disk
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/7|Priority: 10000]ShutdownController: item ended after->237
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:2/7]
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/7|Priority: 0]ShutdownController: start item->ShutdownEvent: Save JSonStorages
THREAD: 25
25|Log.L.log 10/30/18 9:27:40 AM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Start Saving Storage
25|Log.L.log 10/30/18 9:27:40 AM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> ENDED Saving Storage
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/7|Priority: 0]ShutdownController: item ended after->3
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:3/7]
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/7|Priority: 0]ShutdownController: start item->ShutdownEvent: SaveAllStorageHandler
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/7|Priority: 0]ShutdownController: item ended after->2
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:4/7]
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/7|Priority: 0]ShutdownController: start item->ShutdownEvent: ProcessDelayedWrites num=0
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/7|Priority: 0]ShutdownController: item ended after->2
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:5/7]
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/7|Priority: -2147483648]ShutdownController: start item-> Priority: -2147483648
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/7|Priority: -2147483648]ShutdownController: item ended after->3
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:6/7]
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/7|Priority: -2147483648]ShutdownController: start item->ShutdownEventWrapper Thread[Thread-0,5,main] - java.util.logging.LogManager$Cleaner Priority: -2147483648
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/7|Priority: -2147483648]ShutdownController: item ended after->2
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:7/7]
8|org.appwork.shutdown.ShutdownController.log 10/30/18 9:27:40 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> Shutdown Hooks Finished`

**Comment by jaymoulin** [comment]
I see no problem with the docker image and your issue seems similar to #16. 
I suggest you delete everything (configuration folders + container) + create your container without the user part.
If problem persists, contact jdownloader team

**Comment by Sirfrancis17** [comment]
i delete image, container, folder and i change install folder (inside of Downloads) but doesn't work
i try create another account and execute "docker exec jdownloader configure xxx" with the new data but doesn't work

**Comment by jaymoulin** [comment]
Then contact jdownloader team ;)

**Comment by Sirfrancis17** [comment]
What is the problem that should be exposed?

**Comment by jaymoulin** [comment]
Give them logs, they like it

**Comment by Sirfrancis17** [comment]
The log of the last message is fine?

**Comment by jaymoulin** [comment]
Open an issue with you problem and logs and all the information they ask you to give (unlike what you did when opening this issue ;))

**Comment by Sirfrancis17** [comment]
ok thanks
