### ISSUE TITLE
docker always restart

### ISSUE THREAD

**Issue by Sirfrancis17** [jaymoulin/docker-jdownloader#18]
Hello again
As explained in related #17 , I try to use this wonderful image on an arm64 device with librelec
jdownloader says that they have no incidence with the portal
I still try to solve the problem. Now I have noticed that the docker container, if I do not put my user data, keeps working 30s. On the other hand, if I put my data of jdownloader, the service, it restarts every 12-16 seconds
This can help solve the problem?

![image](https://user-images.githubusercontent.com/44566906/47790154-bcb81600-dd16-11e8-837c-29946c20ff56.png)

**Comment by Sirfrancis17** [comment]
Thank you for answering. 
If it is because of that then the problem persists from the incidence #17
I guess there is no solution
Thanks anyway

**Comment by jaymoulin** [comment]
There is a solution but I can't help as I don't have the necessary information and you're problem seems related to jdownloader and NOT this image. You should not open issue here but to jdownloader team so they can help you.

**Comment by Sirfrancis17** [comment]
Ok
