### ISSUE TITLE
Problem with special characters (Umlaute, german)

### ISSUE THREAD

**Issue by der-optimist** [jaymoulin/docker-jdownloader#20]
Hello jaymoulin,
I really like your work and I'm 99% happy with it :-)
I live in Germany, so many of the file names I download contain special characters like ä ö ü Ä ß ...
These are shown as a ? in the host system (openmediavault 4.1.16-2) and samba/cifs doesn't show the name at all (it uses 2VH5OD~P.MP4 for example).
I use UTF-8 in openmediavault - what does the jdownloader container use? Or did I just not understand how to set the charset for the container?

**Description**

**Command line I used to start the container**
Started via GUI, but according to this command:
docker run -d --restart=always -v ~/Downloads:/root/Downloads -v ~/jdownloader/cfg:/opt/JDownloader/cfg --name jdownloader -u $(id -u):$(id -g) jaymoulin/jdownloader

**Steps to reproduce the issue:**
1. use openmediavault 4.1.16-2
2. use this docker-container to download a file with a german umlaut (äöüÄÖÜ), e.g.:
   https://www.youtube.com/watch?v=wtJGAJrvFu8

**Describe the results you received:**
Filenames like "K?ln.mp4" instead of "Köln.mp4"
If I do "mv K?ln.mp4 Köln.mp4" everything is fine, so the special characters work if they are encoded correctly.

<details>
<pre>
(paste logs)
</pre>
</details>

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**
```
0.6.0
```
Thank you

**Comment by jaymoulin** [comment]
I don't think this is related to neither docker nor jdownloader, nor my docker-jdownloader image. Do you have something I can make some tests out of?

**Comment by der-optimist** [comment]
Thank you for your answer. When I copy a file with these characters via cifs or rsync, I do not have this problem. Only with the files downloaded by jdownloader - that's why I searched here. Could you please describe what you need for a test? Maybe you could download the file I linked and see what happens, it contains an ä in the name.What charset/encoding does the docker container use? Or should it take the one of the host system?Thank you!


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Jay MOULIN <notifications@github.com> Datum: 05.01.19  17:52  (GMT+01:00) An: jaymoulin/docker-jdownloader <docker-jdownloader@noreply.github.com> Cc: der-optimist <j_eggler@arcor.de>, Author <author@noreply.github.com> Betreff: Re: [jaymoulin/docker-jdownloader] Problem with special characters (Umlaute, german) (#20) 
I don't think this is related to neither docker nor jdownloader, nor my docker-jdownloader image. Do you have something I can make some tests out of?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jaymoulin/docker-jdownloader","title":"jaymoulin/docker-jdownloader","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jaymoulin/docker-jdownloader"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jaymoulin in #20: I don't think this is related to neither docker nor jdownloader, nor my docker-jdownloader image. Do you have something I can make some tests out of?"}],"action":{"name":"View Issue","url":"https://github.com/jaymoulin/docker-jdownloader/issues/20#issuecomment-451671069"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jaymoulin/docker-jdownloader/issues/20#issuecomment-451671069",
"url": "https://github.com/jaymoulin/docker-jdownloader/issues/20#issuecomment-451671069",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by der-optimist** [comment]
Thank you for your answer. 
When I copy a file with these characters via cifs or rsync, I do not have this problem. Only with the files downloaded by jdownloader - that's why I searched here. 
Could you please describe what you need for a test? Maybe you could download the file I linked and see what happens, it contains an ä in the name.
What charset/encoding does the docker container use? Or should it take the one of the host system?
Thank you!

**Comment by der-optimist** [comment]
No, I use an Odroid HC1 (same as XU4) with an Exynos 5422 => ARMv7 (Cortex-A15 + Cortex-A7). 
Should the docker container use the charset/encoding of the host system or can it be defined separately?

**Comment by jaymoulin** [comment]
I didn't build an armv7 image. Do you mind giving me the docker image id?

**Comment by der-optimist** [comment]
Oh ok. I searched google for "jdownloader docker arm" and found your image. As I saw "multiarch, arm, armv7,..." on top of the page, I was happy :-) 
I'm not (yet) very familiar with docker - I hope I get the right info for you:

output of "docker images --no-trunc"
REPOSITORY TAG IMAGE ID CREATED SIZE
jaymoulin/jdownloader latest sha256:c25e336eb651600bf100a52f8e6cf40b129277ac6f5614abc4c3f0141300a49e 2 months ago 213MB
`docker images REPOSITORY TAG IMAGE ID CREATED SIZE jaymoulin/jdownloader latest c25e336eb651 2 months ago 213MB`

output of "docker images"
REPOSITORY TAG IMAGE ID CREATED SIZE 
jaymoulin/jdownloader latest c25e336eb651 2 months ago 213MB

**Comment by jaymoulin** [comment]
You're using the armv6 image which is compatible with armv7. This is the only image that does not use the same base image as the other due to a performance issue with armv6 and latest openjdk with jdownloader. My guess is, something in the base image must be interfering with your encoding.

I don't think I'll spend so much time on recompiling old jdk versions do fix a minor issue like this one but I leave this open for someone to take a look

**Comment by der-optimist** [comment]
OK thank you
