### ISSUE TITLE
"Permission denied"/"No such file or directory" when running `sudo docker exec jdownloader configure`

### ISSUE THREAD

**Issue by amrazi** [jaymoulin/docker-jdownloader#21]
When I attempt to run the command
`sudo docker exec jdownloader configure email@email.com password`
 after having downloaded the container, I get 

`cp: can't create '/opt/JDownloader/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json': Permission denied
sed: /opt/JDownloader/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json: No such file or directory`

And the JDownloader website does not recognize any running JDownloader2 instances.

**Logs**

<details>
<pre>
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
</pre>
</details>

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
0.6.1-arm64
```

**Comment by jaymoulin** [comment]
Looks like you have a permission error on your volume + you seems to use docker with docker rights instead of your own user. What command did you use to create your container?

**Comment by amrazi** [comment]
`docker run -d --restart=always -v ~/Downloads:/root/Downloads -v ~/jdownloader/cfg:/opt/JDownloader/cfg --name jdownloader -u $(id -u):$(id -g) jaymoulin/jdownloader`

**Comment by jaymoulin** [comment]
with or without sudo ?

Could you check that the rights for `~/jdownloader/cfg` matches the user for `$(id -u):$(id -g)`

**Comment by amrazi** [comment]
I initially used without sudo, although with it gives the same message. 

Running `ls -l` in `~/jdownloader/cfg` returns `drwxr-xr-x 2 root root 4096 Jan 28 15:06 cfg`

**Comment by jaymoulin** [comment]
Yep, rights problem. Your cfg directory has write rights for root but you're running your container with your own user. Either change owner of your cfg directory or use a container without the `-u XXXX` param, but you'll probably have to recreate your container

**Comment by amrazi** [comment]
That was it! Started fresh by removing all containers, running `docker run -d --restart=always -v ~/Downloads:/root/Downloads -v ~/jdownloader/cfg:/opt/JDownloader/cfg --name jdownloader -u $(id -u):$(id -g) jaymoulin/jdownloader`, and running ` sudo docker exec jdownloader configure email@email.com password` with no error.

However, the JDownloader website does not recognize any running JDownloader2 instances.

**Comment by amrazi** [comment]
Spoke too soon, the website sees it. Thank you for the help and making this container!

**Comment by amrazi** [comment]
I am actually working with a reinstall of this on a fresh OS, and I am running into this again, however, taking ownership does not seem to help. What insight does `drwxr-xr-x 2 root root 4096 Jan 28 15:06 cfg` lend and what `user:group` should I aim for?

I have used `rock64:docker`, `rock64:rock64`, and `rock64:root` to no avail (where rock64 is my user).

**Comment by jaymoulin** [comment]
Your `cfg` folder is created as root (only user that can write file into it) and you created your container with `-u XXX` parameter which mean `run with user rights`. 
- Delete your container
- start without `-u` parameter OR give correct rights permissions to your folders
