### ISSUE TITLE
Downloads won't save

### ISSUE THREAD

**Issue by schlegp** [jaymoulin/docker-jdownloader#24]
I have the docker running with the normal commands:
docker run -d --restart=always -v /media/schlegp/Videos:/root/Downloads -v ~/jcfg:/opt/JDownloader/cfg --name jdownloader -u $UID:$(id -g) jaymoulin/jdownloader

The Settings get saved just fine, but downloads are nowhere to be found.
"/Videos" is a mounted USB drive that got auto-mounted by linaro.

When choosing a path under /opt/JDownloader/cfg in JDownloader the download works as expected.

I tried cloning chown and chmod from this folder to the download folder but that didn't change anything.

How do I need to setup my folders that it works?

**Comment by jaymoulin** [comment]
You're mistaking `/Video` with `/root/Downloads` or `/media/schlegp/Videos`.

You can find your downloads by doing this :
```bash
docker exec -ti jdownloader sh
cd /Videos
ls
```

And retrieving them by moving your files in `/root/Downloads`

To avoid this confusion in your next downloads, I suggest you change your default download folder from `/Videos` to `/root/Downloads`

**Comment by schlegp** [comment]
Thanks, that was definitely the problem, I was just too blind to notice. JDownloader Downloads by default to /opt/jdownloader/Downloads but my volume was mapped to /root/Downloads, that's why I couldnt find the file.
