### ISSUE TITLE
9kw.eu User Api Key

### ISSUE THREAD

**Issue by wusa88** [jaymoulin/docker-jdownloader#25]
Hello,

I tried to use the 9kw.eu Api Key with MyJDownloader. I can enter the api key and also save but no captch will be solved automatically.

I have tried 3 different Api Keys. Unfortunately, I do not know which is really right.

There are so many Api Keys. On the MyJDownloader page is the following:
"Captcha9kwSettings: Api Key
Your (User) ApiKey from 9kw.eu "

At 9kw.eu I have a whole list full of Api Keys:

General: API

Specifics: 9kwGUI - 9kw client - JDownloader 1 - JDownloader 2 - Pyload - Android - Fritz! Load - Mipony - jCatGUI - Candisoft - iMacros - CaptchaSolver - Plowshare - GUI - CLI - Windows Phone - Windows 8 - iPad - iPhone - ShareDownloader - Win32 GUI

Which Api Key is the right one for your Docker Image an the MyJdownloader side?

**Comment by jaymoulin** [comment]
This docker image runs a Jdownloader 2 headless instance.

For further information about 9kw.eu or JDownloader, I suggest you contact them on their respective supports.
