### ISSUE TITLE
JDownloader stucked in restart loop

### ISSUE THREAD

**Issue by bobrooney** [jaymoulin/docker-jdownloader#27]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
0.7.0-arm64
```

**Description**

JDownloader keeps restarting every 12 sec after initial update.

**Command line I used to start the container**
docker run -d --restart=always -v ~/downloads:/root/Downloads -v ~/apps/jdownloader/cfg:/opt/JDownloader/cfg --name jdownloader -u 0:0 jaymoulin/jdownloader:0.7.0-arm64v8

**Steps to reproduce the issue:**
1. docker run -d --restart=always -v ~/downloads:/root/Downloads -v ~/apps/jdownloader/cfg:/opt/JDownloader/cfg --name jdownloader -u 0:0 jaymoulin/jdownloader:0.7.0-arm64v8
2. docker exec jdownloader configure "my-email" "my-pass"
(checked zillion times)

**Describe the results you received:**
I cannot connect with my.jdownloader
"docker ps" shows that container is up only 12 seconds.

**Describe the results you expected:**
JDownloader on my dashboard in my.jdownloader

**Additional information you deem important (e.g. issue happens only occasionally):**
My device: Beeling Mini MX S905
OS: Coreelec 9.0.1
Docker version: 18.09.1, build 18.09.1
**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
UpdateClient Proxy Vole 47
Update Message: Check for updates
Update Message: Validating Installation.
This can take up to 5 minutes...
Update Progress: -1%
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
UpdateClient Proxy Vole 49
Update Message: Check for updates
Update Message: Validating Installation.
This can take up to 5 minutes...
Update Progress: -1%
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
UpdateClient Proxy Vole 53
Update Message: Check for updates
Update Message: Validating Installation.
This can take up to 5 minutes...
Update Progress: -1%
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
UpdateClient Proxy Vole 49
Update Message: Check for updates
Update Message: Validating Installation.
This can take up to 5 minutes...
Update Progress: -1%
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory
JarHandlerWorkaroundOracle:replaceLauncherFactory
JarHandlerWorkaroundOracle:replaceURLClassPath
JarHandlerWorkaroundOracle:replacejarHandler
JarHandlerWorkaroundOracle:replaceLoaders:1
JarHandlerWorkaroundOracle:replaceLoader:0:handler
JarHandlerWorkaroundOracle:replaceLoader:0:handler:jar:file:/opt/JDownloader/JDownloader.jar!/
sun.Desktop: null
XDG_CURRENT_DESKTOP: null
KDE_FULL_SESSION: null
KDE_SESSION_VERSION: null
DESKTOP_SESSION: null
GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory
Multiple LogControllers Detected: org.jdownloader.logging.LogController
Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
UpdateClient Proxy Vole 47
Update Message: Check for updates
Update Message: Validating Installation.
This can take up to 5 minutes...
Update Progress: -1%

</pre>
</details>

**Comment by jaymoulin** [comment]
Remove your actual container
Remove the `-u 0:0` flag from your command (it's not valid and default user is already root)
Put full path to your volumes (-v flags) instead of `~` as they're not correctly handled by docker.
Once done you'll need to reconfigure your password with the `docker exec jdownloader configure "my-email" "my-pass"`.

Let me know
