### ISSUE TITLE
Jdownloader crashes / freezes system on omv

### ISSUE THREAD

**Issue by Lowrider0** [jaymoulin/docker-jdownloader#28]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
0.7.0-armhf
```

**Description**

I run jdownloader docker on omv, Raspberry Pi 3B+, i can run everything and connect via myjdownloader.org, start downloading but after a few minutes the system freezes and the Raspberry Pi disconnects from the network. I have to reboot the system. What can i do about that?

Here is the log file from the image on docker (OMV):
[docker_log.txt](https://github.com/jaymoulin/docker-jdownloader/files/3174814/docker_log.txt)
 
Any help is greatly appreciated, as i have no idea how to make this work.

**Comment by jaymoulin** [comment]
Your description indicates everything is working. Your crash probably comes from something else and you'll have to check if your device has sufficient resources to run all your programs.
