### ISSUE TITLE
New location for daemon.sh?

### ISSUE THREAD

**Issue by trohnjavolta** [jaymoulin/docker-jdownloader#30]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
0.7.1-armhf
```

**Description**

**docker compose part I used to start the container**

jdownloader2:
    command: tini -- /opt/JDownloader/daemon.sh
    container_name: jdownloader2
    environment:
      - PGID=1003
      - PUID=1000
      - TZ=${TZ}
    image: jaymoulin/jdownloader:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/dev-disk-by-label-festplatte/downloads/jdownloads:/opt/JDownloader/downloads
      - /home/dluser/.docker/config/jd2:/opt/JDownloader/cfg

**Describe the results you received:**
Upon creation dockstarter throws this error:

ERROR: for jdownloader2  Cannot start service jdownloader2: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"tini\": executable file not found in $PATH": unknown

**Additional information you deem important (e.g. issue happens only occasionally):**
Did daemon.sh maybe move to another location since it can't be found under /opt/JDownloader?
If so to where?

**Provide some logs (`docker logs jdownloader`)**

no logs since container can't start.

**Comment by jaymoulin** [comment]
Those commands : 
```
$> docker exec -ti jdownloader2 sh
/opt/JDownloader $ ls -la
```

Should show something like that:

```
total 11624
drwxrwxrwx    1 root     root          4096 May 31 05:59 .
drwxr-xr-x    1 root     root          4096 May  2 23:52 ..
-rw-r--r--    1 1001     1001       7947150 May 30 07:45 Core.jar
-rw-r--r--    1 1001     1001             0 May 31 05:59 JD2.lock
-rw-r--r--    1 1001     1001             4 May 31 05:59 JD2.port
-rw-r--r--    1 1001     1001       3756864 May 31 05:59 JDownloader.jar
-rw-r--r--    1 1001     1001             3 May 31 05:59 JDownloader.pid
-rw-r--r--    1 1001     1001           320 May 31 05:59 build.json
drwxr-xr-x    3 1001     1001          4096 May 21 23:12 captchas
drwxr-xr-x    4 1001     1001         36864 May 31 16:09 cfg
-rwxrwxr-x    1 root     root           776 May  2 23:37 daemon.sh
drwxr-xr-x    2 1001     1001          4096 May 25 00:16 extensions
drwxr-xr-x    2 1001     1001          4096 May 11 23:46 java
drwxr-xr-x    4 1001     1001          4096 May 11 23:46 jd
drwxrwxrwx    1 root     root          4096 May 30 07:45 libs
-rw-r--r--    1 1001     1001         32034 May 11 23:45 license.txt
-rw-r--r--    1 1001     1001         39624 May 11 23:45 license_german.txt
drwxr-xr-x    5 1001     1001          4096 May 11 23:45 licenses
drwxr-xr-x    9 1001     1001          4096 May 31 05:59 logs
-rw-rw-r--    1 root     root            76 May  2 23:37 org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json.dist
drwxr-xr-x    3 1001     1001          4096 May 11 23:46 themes
drwxr-xr-x    5 1001     1001          4096 May 31 16:09 tmp
drwxr-xr-x    5 1001     1001          4096 May 11 23:46 translations
drwxr-xr-x    3 1001     1001          4096 May 11 23:42 update
```
If not, you probably mounted a volume to `/opt/JDownloader` when you created your container which may cause your actual issue.

**Comment by trohnjavolta** [comment]
> Those commands :
> 
> ```
> $> docker exec -ti jdownloader2 sh
> /opt/JDownloader $ ls -la
> ```

Since the container isn't started I cannot execute that command. Upon starting the container I get the error message.
There's just a volume mounted to /opt/JDownloader/cfg and to /opt/JDownloader/downloads

**Comment by trohnjavolta** [comment]
Hmm.. ok, so I created the container manually using same volumes as in compose file and it worked.
Sth. wrong at my end, I didn't /opt/JDownloader though... Did you spot any mistakes in my compose file part by any chance?

**Comment by trohnjavolta** [comment]
Ok, leaving away `command: tini -- /opt/JDownloader/daemon.sh` solved it.
