### ISSUE TITLE
CoreELEC - 0.7.1-arm64v8 - restart loop

### ISSUE THREAD

**Issue by AndreSDUS** [jaymoulin/docker-jdownloader#32]
Hi.

There was the same problem, but the User didn't answer and the issue was closed:
https://github.com/jaymoulin/docker-jdownloader/issues/27

I just created this github Account for this problem.
Your container runs without any problems on my rpi and ubuntuserver(vm).

But its not possible to do the same on my aarch64/arm64 box.
I hope you can help me an my issue is correct.
I try to give you all information i got and will check this thread every day in future :)

Kind regards
André; Germany.
*************************************************************************************  
**Specs**

CoreELEC:~ # uname -a
Linux CoreELEC 3.14.29 #1 SMP Sun May 12 15:03:58 BST 2019 aarch64 GNU/Linux

CoreELEC:~ # cat /proc/cpuinfo 
Processor       : AArch64 Processor rev 4 (aarch64)
processor       : 0
processor       : 1
processor       : 2
processor       : 3
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp edsp neon vfpv3 tlsi vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : Amlogic
Serial          : 210b820070d78ef4e0c688a2a025e3a3

CoreELEC:~ # docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        18.09.1
 Built:             Thu May 16 00:20:58 UTC 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       18.09.1
  Built:            Thu May 16 00:20:58 UTC 2019
  OS/Arch:          linux/arm
  Experimental:     false

docker pull jaymoulin/jdownloader:0.7.1-arm64v8

CoreELEC:~ # docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
jaymoulin/jdownloader   0.7.1-arm64v8       2a452c0cda5d        2 weeks ago         123MB
*************************************************************************************  

**Description**

After the first conainter run everything looks good. But after the --restart the jd trys to update ...and shutdown. I have no idea why. I cant understand the log.

I checked the closed issues and change the docker run from ~ to /storage/ and deleted the -u

i got these folder:
/storage/jdownloader/cfg (owner/group:root; rwxr-xr-x)
/storage/Downloads (owner/group:root; rwxr-xr-x)

i got these files: (owner/group: root; rw-r--r--)
org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json (double checked)
org.appwork.utils.logging2.LogConfig.json
org.jdownloader.settings.InternetConnectionSettings.customproxylist.json
org.jdownloader.settings.InternetConnectionSettings.json
org.jdownloader.updatev2.UpdateSettings.json
ProxySelector.proxies.json

*************************************************************************************  
**Command line I used to start the container**

docker run -d --restart=always -v /storage/Downloads:/root/Downloads -v /storage/jdownloader/cfg:/opt/JDownloader/cfg --name jd jaymoulin/jdownloader:0.7.1-arm64v8

docker exec jd configure email password

*************************************************************************************  
**Steps to reproduce the issue:**
1. first start docker run ... okay. log looks good
2. after this = loop
*************************************************************************************  
**Describe the results you received:**
[first run.txt](https://github.com/jaymoulin/docker-jdownloader/files/3281036/first.run.txt)

[--restart loop.txt](https://github.com/jaymoulin/docker-jdownloader/files/3281037/--restart.loop.txt)

*************************************************************************************  

I got these logs with putty and logging. I cant find the real logs ...sorry.
Hopefully i gave you all information. 
I was a bit affraid to open this issue. Cause there are a few closed issue with the "same" problem. But they are from 2018. May be something changed.

again, kind regards. André

**Comment by jaymoulin** [comment]
I don't see any error in your logs. Your instance is updating and restarting as expected by JDownloader.
Did you open an issue on Jdownloader forum? they can read your logfiles and explain what's happening

**Comment by AndreSDUS** [comment]
Hey.

Thanks for response.
The loope repeats until i stop the container.
No. But now i know its not a problem with your contrainer after your check.
I'll post the Problem on jd-forum.

Kind regards

**Comment by jaymoulin** [comment]
It might be a problem with the container (like a missing dependency or whatever). I was just not able to find any problem in your log

**Comment by AndreSDUS** [comment]
Ah okay.

Whats the plan? I can post my problem later on jd-forum and give you a response?

**Comment by jaymoulin** [comment]
Jdownloader forum if the best place to get help with JDownloader. I only did a Docker port.
If something is not working, they'll be able to find it. 
If it's in JDownloader, they'll fix it and it should automatically update in your container.
If it's due to a dependency, they'll probably ask you to change/update that dependency, and this will probably belong to me.

You can post your issue as a comment for me to follow the progression and for users to have more information on how to fix this

**Comment by AndreSDUS** [comment]
okay. sounds great! :)
awesome support!
stay tuned :)

**Comment by AndreSDUS** [comment]
Hey.

no chance. no account activation, no response from admin.

We can close this issue. 
Thanks for your support.
kind regards

**Comment by AndreSDUS** [comment]
i got an answer by mail from an admin ...lets reopen this thread. i'm happy!

answer translated by google for you:

"
Because of your problem. Please zip the complete logs folder and send me this.
Docker may NOT create / monitor the process ID itself, but must use the JDownloader.pid file
Check in the JDownloader, because during the start / update of the JDownloader the JD
can restart automatically (several times).

From daemon.sh this looks wrong to me
PID = $!
wait $ PID
wait $ PID

the PID can change and thus the PID is no longer correct after the update.
"

i want to do what the admin said. i'll give you a response ...if it works or may be you have to change something.

kind regards!
André

**Comment by AndreSDUS** [comment]
Link to board.jd

https://board.jdownloader.org/showthread.php?p=443849#post443849

But its in german.
I want to give you an update, if someone gives me an answer about a solution.

kind regards

**Comment by jiaz83** [comment]
I guess the loop comes from daemon.sh.
JDownloader starts and detects a new update and starts to install it. During installation, JDownloader may restart itself several times.
PID = $! -< contains the initial PID of the process finding the update
wait $ PID <JDownloader restarts itself
wait $ PID <PID no longer valid
then the container stops/restarts and the update might not be finished yet, resulting in endless loop while trying to install/finish the update

I've tried to create little script that handles the changing PID
=================================================================
PIDFile="/home/daniel/Projekte/beta2/JDownloader.pid"
while :
do
if [ -f $PIDFile ]; then
CurPID=$(<"$PIDFile")
echo "Current PID is $CurPID"
tail --pid=$CurPID -f /dev/null
else
echo "wait for JDownloader"
sleep 30
if [ -f $PIDFile ]; then
echo "retry"
else
echo "no JDownloader running"
break
fi
fi
done

**Comment by jaymoulin** [comment]
@AndreSDUS Made a 0.7.2 image that may fix this issue. As I am not able to reproduce this, could you please try it out?

@jiaz83 Thanks for your contribution. What makes 30s a good waiting value? How can JDownloader process update if its main process finished? How often the 'JDownloader.pid' file is updated and how many time does it take to update it (how can I know for sure its value is the actual PID)?

**Comment by jiaz83** [comment]
@jaymoulin: JDownloader main process checks for available/pending updates. Launches a 2nd instance that verifies/tests the updates. At that moment two processes are running. Now the 2nd instance reports that the verification/testing is successful and the main process stops itself and the 2nd instance now applies/installs the update to the main installation and after that launches new main process (3rd instance) and then stops itself. 30 secs is just a *should be enough* but of course the script could be optimized to also check for the 2nd running instance as well. JDownloader always writes JDownloader.pid on startup relative to its JDownloader.jar file.
In case you got more questions, just ask or contact us.
Thanks for your help and contribution!

**Comment by AndreSDUS** [comment]
@jaymoulin Thanks. But nothing changed. Same logs, same content, same loop.

**Comment by jaymoulin** [comment]
Are you sure you downloaded the latest image and recreated your container?

**Comment by AndreSDUS** [comment]
Yes. 
docker rm [container]
rocker rmi [image]
docker pull jaymoulin/jdownloader:0.7.2-arm64v8
docker run (...) jaymoulin/jdownloader:0.7.2-arm64v8
docker ps (-a)
da6d61262dd5        jaymoulin/jdownloader:0.7.2-arm64v8   "tini-static -- /opt…"   11 minutes ago      Exited (0) 9 minutes ago                            jd

**Comment by jaymoulin** [comment]
You should have "Waiting for jdownloader" in your logs then. Can you confirm?

**Comment by jiaz83** [comment]
@jaymoulin just to be sure, you did modify the line PIDFile ... right?

**Comment by jaymoulin** [comment]
> @jaymoulin just to be sure, you did modify the line PIDFile ... right?

Yes

**Comment by AndreSDUS** [comment]
@jaymoulin No. 

Container log = loop
[container log.txt](https://github.com/jaymoulin/docker-jdownloader/files/3344892/container.log.txt)

inside Container = JD Logs
[1561972731974_Mon, Jul 1, 2019 09.18 +0000.zip](https://github.com/jaymoulin/docker-jdownloader/files/3344893/1561972731974_Mon.Jul.1.2019.09.18.%2B0000.zip)

**Comment by jiaz83** [comment]
the log shows installation of pening update
17|org.jdownloader.update.UpdateManager.log 7/1/19 9:38:13 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Test
17|org.jdownloader.update.UpdateManager.log 7/1/19 9:38:13 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Running
17|org.jdownloader.update.UpdateManager.log 7/1/19 9:38:13 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> File exists
17|org.jdownloader.update.UpdateManager.log 7/1/19 9:38:15 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> Validate:  OK
17|org.jdownloader.update.UpdateManager.log 7/1/19 9:38:15 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> SelfTest Results:
OK

@AndreSDUS: do not share your JD logs public. the container log is okay but @jaymoulin  was asking for the docker log

**Comment by jaymoulin** [comment]
Looks like the PID file is deleted between Main process stops and JDownloader updates.

Made a new 0.7.2. @AndreSDUS can you retry (delete image + container)?

**Comment by AndreSDUS** [comment]
sure!
removed container and image
pull again jdownloader:0.7.2-arm64v8
run

now i got "waiting..."

[container_new.txt](https://github.com/jaymoulin/docker-jdownloader/files/3344986/container_new.txt)

but same loop

**Comment by jaymoulin** [comment]
New image with a longer timeout but this is just luck... That's not how things are supposed to work

**Comment by AndreSDUS** [comment]
same: wating (..) = 17 seconds...loop

may be we can't  finde a solution. its okay for me. Its not necessary to spend hours just for me.
we can stop. what do you think?

**Comment by jaymoulin** [comment]
@AndreSDUS It's not just you, you reported an issue on a FLOSS product so it may affect thousand of users. As you actually are the single one being able to reproduce it and helping us debugging the issue, there is no reason to stop here.

@jiaz83 Is it possible the update process never triggers and/or never creates the PID file?

@AndreSDUS I created another image with debug information that should display the PID files + running processes. Could you try it out?

**Comment by AndreSDUS** [comment]
Okay. Sounds good :)

with new image
[ce_docker_124104.log](https://github.com/jaymoulin/docker-jdownloader/files/3345169/ce_docker_124104.log)

this is a puttylog:  first run + restart + loop

check line 2445 - 2448

pid file
ls: /opt/JDownloader/JDownloader.pid: No such file or directory
testing PID
cat: can't open '/opt/JDownloader/JDownloader.pid': No such file or directory

**Comment by jaymoulin** [comment]
Compiled a new image. This should wait for all spawned processes.

**Comment by AndreSDUS** [comment]
[ce_docker_131613.log](https://github.com/jaymoulin/docker-jdownloader/files/3345268/ce_docker_131613.log)

new image
this is a puttylog: first run + restart + loop

"Waiting for jdownloader to finish"

loop

**Comment by jiaz83** [comment]
@jaymoulin: the pid file is deleted on shutdown and created on startup. the part of bash script works perfectly fine for my system and tested installation of updates/restart of JDownloader. 
log is *strange* because there is no *waiting for new pid* in it?
did you test the updated script on your own system because it should work on every setup the same.
basically check for PID file, then read PID number and wait for it. when processed is finished, then loop. the logs simply stops after *waiting for jdownloader to finish* but there is no wait for new pid log entries? maybe difference as /bin/sh might be either sh shell or symnlink to bash.?!

**Comment by jaymoulin** [comment]
@jiaz83 Should but don't. This is particularly true in a docker context as the full environment is isolated. This issue wouldn't exist if the behaviour was strictly the same ;)

As I can experience on my setup : a neverending process `java -Djava.awt.headless=true -jar JDownloader.jar -afterupdate` is spawned right after the update. A Jdownloader.pid file is (or not depending on the setup (@AndreSDUS has a log with this file not created but an update process running)) created with the PID of this 'afterupdate' process.

I don't think bash or sh would interfere with this. The daemon is not waiting because the new thread is not a child of the daemon but one of the dead main process which results to a zombie thread, in my opinion.

**Comment by jiaz83** [comment]
The behaviour is always the same. Updates always happen the same way. And you've tested it by yourself and the *afterupdate* process also creates a PID. you cannot use WAIT as this only works for processes started within that shell. That's why I replaced that part with *tail --pid=$CurPID -f /dev/null* that also works with external started processes.There are also other methods to wait for running PIDs.
Can you share your *current* daemon.sh version? The whole daemon.sh script should only exit/stop after JDownloader has stopped running

**Comment by jaymoulin** [comment]
```sh
#!/bin/sh

trap 'kill -TERM 1' TERM INT
rm -f /opt/JDownloader/JDownloader.jar.*
rm -f /opt/JDownloader/JDownloader.pid

# Debugging helper - if the container crashes, create a file called "jdownloader-block.txt" in the download folder
# The container will not terminate (and you can run "docker exec -it ... bash")
if [[ -f /root/Downloads/jdownloader-block.txt ]]; then
    sleep 1000000
fi

# Check if JDownloader.jar exists, or if there is an interrupted update
if [[ ! -f /opt/JDownloader/JDownloader.jar ]] && [[ -f /opt/JDownloader/tmp/update/self/JDU/JDownloader.jar ]]; then
    cp /opt/JDownloader/tmp/update/self/JDU/JDownloader.jar /opt/JDownloader/
fi

java -Djava.awt.headless=true -jar /opt/JDownloader/JDownloader.jar &
PID=$!
echo "PID : ${PID}"
wait ${PID}
echo "Process stopped"
wait ${PID}

# Check if JDownloader.jar exists, or if there is an interrupted update
if [[ -f /opt/JDownloader/tmp/update/self/JDU/JDownloader.jar ]]; then
    sleep 2
    PIDS=$(pgrep java)
    while [[ "${PIDS}" ]]; do
        for PID in ${PIDS}; do
            echo "Waiting for jdownloader to finish PID : ${PID}"
            wait ${PID}  # not a process of main thread, so exits
            PIDS=$(pgrep java) # always returns the same -afterupdate process
            wait ${PID}
        done # result in infinite loop as -afterupdate never ends
    done
fi

EXIT_STATUS=$?
```
On my system : jdownloader.pid contains the neverending `-afterupdate` process
On @AndreSDUS system : jdownloader.pid file does not exist as this state
On alpine, tail can't work with pid

From a system POV a thread should not be spawned if its parent can't handle it. If the parent dies, its child should die as well otherwise it would result into a kernel panic

**Comment by jiaz83** [comment]
May I ask why you don't simply check for /opt/JDownloader/JDownloader.pid and read the PID from it? Much simpler. And also replace WAIT with "tail --pid=$CurPID -f /dev/null" to wait for the PID.
You can also use (http://blog.joncairns.com/2013/03/wait-for-a-unix-process-to-finish/)

> PID=<pid to watch>
while s=`ps -p $PID -o s=` && [[ "$s" && "$s" != 'Z' ]]; do
    sleep 1
done

If you don't want to make it that complicated, you can also simply add a sleep 60 before EXIT_STATUS

Your script still fails when the update finishes betweend wait and if condition asn you no longer check for new main process.

**Comment by jiaz83** [comment]
You can also add -norestart as parameter and JDownloader will not allow any restart. That way the installation of an update will always result in restarted container

**Comment by jaymoulin** [comment]
> May I ask why you don't simply check for /opt/JDownloader/JDownloader.pid and read the PID from it? Much simpler. And also replace WAIT with "tail --pid=$CurPID -f /dev/null" to wait for the PID.
> You can also use (http://blog.joncairns.com/2013/03/wait-for-a-unix-process-to-finish/)
> 
> > PID=
> > while s=`ps -p $PID -o s=` && [[ "$s" && "$s" != 'Z' ]]; do
> > sleep 1
> > done
> 
> If you don't want to make it that complicated, you can also simply add a sleep 60 before EXIT_STATUS
> 
> Your script still fails when the update finishes betweend wait and if condition asn you no longer check for new main process.

As I previously explained:
- `/opt/JDownloader/JDownloader.pid` does not exist at this state on @AndreSDUS system, so I can't read that file. Also, even if it exists on my system, it gives me a neverending process which result jdownloader to not restart
- I can't `tail --pid ` as --pid does not exist on alpine system

Also:
I can't `ps -p` as -p does not exist on alpine system.
By the way, I already tested a longer timeout for update process to finish but it doesn't change anything on @AndreSDUS system (and also is a 'lucky' fix and that's not how things work).

> You can also add -norestart as parameter and JDownloader will not allow any restart. That way the installation of an update will always result in restarted container

Do you mean the main process will exit when the update is finished?

**Comment by jiaz83** [comment]
> Do you mean the main process will exit when the update is finished?
no, the update process no longer autorestarts to install the update.

Without -norestart
1.) main process finds/downloads the update
2.) 2nd (selftest) process is launched that tests/verifies the downloaded update
3.) main process launches 3rd 'afterupdate' process and stops itself. 
4.) 'afterupdate' applies the update to the main installation

With -norestart
1.) main process finds/downloads the update
2.) main process tests/verifies the downloaded updated, launches new 'afterupdate' process that applies the update to main installation
3.) main process finds no available/pending update and starts

The 'helper' process is required in order to replace/update the main files that are opened by JDownloader.jar as you cannot alter them while JDownloader is running(on Windows) and you can't replace the file in a way that only a new instance will see the new version of the file while the running instance still sees the old files.

I will check why there is no JDownloader.pid for 'afterupdate' step as it should be there.

**Comment by AndreSDUS** [comment]
jfyi: feel free to give me any instruction. 

(i'm offline until 17.00h)

**Comment by jaymoulin** [comment]
@AndreSDUS Recomplied 0.7.2 with -norestart parameter. If I understand correctly, the container should restart 3 times as the update process will be handled by containerd instead of java/jdownloader. JDownloader should execute each task separately as the main process.

@jiaz83 There is a JDownloader.pid file on the afterupdate step on my system but the process indicated in it never ends. The file, however, is not existing on @AndreSDUS system after the main process exits

**Comment by jiaz83** [comment]
@jaymoulin: Ah, now I understand. Sorry for the misunderstanding. The 'afterupdate' process of course never ends as it's the new main process for now. The parameter afterupdate just informs JDownloader that this process is the result from an installation of an update.
JDownloader process keeps running until
1.) you kill/stop it manually 
2.) you restart it manually 
3.) you want to install available/pending updates

**Comment by AndreSDUS** [comment]
new image

[ce_docker_163135.log](https://github.com/jaymoulin/docker-jdownloader/files/3346082/ce_docker_163135.log)

= loop

**Comment by jiaz83** [comment]
@jaymoulin: with -norestart, there is a sleep required, as the new process still has to apply the update

**Comment by jaymoulin** [comment]
@jiaz83 Maybe you should investigate on something. This is really not normal a process could die and spawn other processes without controlling it.

@AndreSDUS I compiled a new image with -norestart AND jdownload.pid waiting process. But, once again, this is just luck that the process could perform in the allowed timeout.THIS MUST produce a jdownloader.pid file otherwise, you'll end up with a restart loop (waiting for a neverending process to finish OR considering the process is not running since no pid file exists)

**Comment by jiaz83** [comment]
> Maybe you should investigate on something. This is really not normal a process could die and spawn other processes without controlling it.
The process doesn't simply die. It starts a new process and then gracefully shuts down itself. A restart method is not that unusual for applications. Even systemd perfectly supports this type of applications

**Comment by AndreSDUS** [comment]
[ce_docker_203919.log](https://github.com/jaymoulin/docker-jdownloader/files/3346923/ce_docker_203919.log)

new image
but loop as well.

**Comment by jaymoulin** [comment]
@AndreSDUS Your logs doesn't match the expected log. You should see `Process stopped` and `PID : XX` in your logs with the latest compiled image. I recompiled the image as the waiting process feature seems not to be uploaded

**Comment by AndreSDUS** [comment]
@jaymoulin 

new image

[ce_docker_165158.log](https://github.com/jaymoulin/docker-jdownloader/files/3350711/ce_docker_165158.log)

e.g.
Process stopped
PID : 10

**Comment by jaymoulin** [comment]
@AndreSDUS Recompiled with restart and process waiting. If this doesn't work, I don't know what to do since this follows all @jiaz83 requirements

**Comment by jiaz83** [comment]
@jaymoulin: I'm missing (maybe I'm blind) sort of *wait* and *retry* messages where the script checks for new PID/Process. Would be good to include *now wait x secs* , *check for PID/Process*...debug messages.

**Comment by jaymoulin** [comment]
@jiaz83 Already exists

```
echo "Waiting for jdownloader to finish PID : ${PID}"
sleep 15
```

**Comment by AndreSDUS** [comment]
Hello

new image

[ce_docker_101221.log](https://github.com/jaymoulin/docker-jdownloader/files/3353906/ce_docker_101221.log)

**Comment by jaymoulin** [comment]
@AndreSDUS Can't do anything more. JDownloaded.pid file is not created in the allowed 15 sec timeout.
Timeout should not be a fix, this is just pure luck. I think @jiaz83 should investigate for subprocesses to be launched by main process before exiting so events could be correctly sent to the system OR each step of the update process could be launched by the main process instead of subprocesses.
Either way should fix your issue without any change to the code. Removing 0.7.2 images

**Comment by AndreSDUS** [comment]
i installed your container on a ubuntu1804-headless and compared the logs.

Its not possible to update JD in the first round on the coreelec box.

coreelec: 
Update Progress: 58.079%
Update Message: Installation in progress - please wait... 
= 3 Seconds later = Shutdown; loop


ubuntu: 
Update Progress: 100%
Update Message: Finalizing installation...
...update....after may be 10 seconds = 

55|Log.L.log 7/3/19 8:22:50 AM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.customdeviceips.json

Jdownloader availibe on https://my.jdownloader.org/ = OKAY

jfyi

**Comment by jiaz83** [comment]
@jaymoulin: I will try to write script that monitor both process/PIDs

> should investigate for subprocesses to be launched by main process before exiting so events could be correctly sent to the system OR each step of the update process could be launched by the main process instead of subprocesses.

the main process doesn't exist before the 2nd process runs. both processes run in parallel and once the 2nd process has verified/tested the update, the main process stops, so the 2nd process can apply/install the update. the main process has to stop as the update may have to modify/add/remove files. there is no issue with this. launching a helper process to install updates is perfectly normal way. Just some examples (Chrome, Firefox, Thunderbird, nearly every Windows application).

**Comment by jaymoulin** [comment]
> @jaymoulin: I will try to write script that monitor both process/PIDs
> 
> > should investigate for subprocesses to be launched by main process before exiting so events could be correctly sent to the system OR each step of the update process could be launched by the main process instead of subprocesses.
> 
> the main process doesn't exist before the 2nd process runs. both processes run in parallel and once the 2nd process has verified/tested the update, the main process stops, so the 2nd process can apply/install the update. the main process has to stop as the update may have to modify/add/remove files. it's not best practice (or even possible at all, eg Windows) to replace/remove/modify files AND executables while the process is still running.
> there is no issue with this. launching a helper process to install updates is perfectly normal way.
> Chrome, Firefox, Thunderbird, Windows applications...all of them are using helper processes to install the update.

I want to trust you but that's clearly not happening as revealed by the logs. Jdownloader.pid file is not created after the main process ends OR may possibly be created in a random timeout between 15 and 30 seconds. All process that I know either runs thread before exiting or write state in a registry/file/cache/whatever.

Here's the actual state of the script:

```sh
java -Djava.awt.headless=true -jar /opt/JDownloader/JDownloader.jar &
PID=$!
echo "PID : ${PID}"
wait ${PID}
echo "Process stopped"
wait ${PID}

sleep 15
# Check if JDownloader.jar exists, or if there is an interrupted update
if [[ -f /opt/JDownloader/JDownloader.pid ]]; then
    PID=$(cat /opt/JDownloader/JDownloader.pid)
    while [[ "${PID}" ]]; do
       while [[ "$(ls -la "/proc/${PID}/fd/2" 2> /dev/null | wc -l)" -ge 1 ]]; do
           echo "Waiting for jdownloader to finish PID : ${PID}"
           sleep 15
       done
       if [[ -f /opt/JDownloader/JDownloader.pid ]]; then
           PID=$(cat /opt/JDownloader/JDownloader.pid)
       else
           PID=0
       fi
    done
fi

EXIT_STATUS=$?
```

After `process stopped`, I was not able to have an existing JDownloader.pid file without a minimum 15 sec timeout. I don't think this should ever happen

**Comment by jiaz83** [comment]
@jaymoulin:
/opt/JDownloader/JDownloader.pid only exists for the main process. 
It highly depends on system performance/update size how long it will take to process/install. 
A full installation can only take a few seconds on fast system or up to several minutes on slow machine. For example if there is no hardware accelaration support for AES, or using non optimized routine for SHA this will increase required time a lot. I will rewrite the script to check/monitor main process and the *helper* process. 
Thanks for the script, I will use it as basis for the update one

**Comment by jaymoulin** [comment]
@AndreSDUS New image with a scanning process features (regardless of jdownloader)

**Comment by AndreSDUS** [comment]
@jaymoulin 

pulled without container tag = latest

[ce_docker_04_115528.log](https://github.com/jaymoulin/docker-jdownloader/files/3358803/ce_docker_04_115528.log)

loop

**Comment by jaymoulin** [comment]
@AndreSDUS Wrong image. You have to pull `jaymoulin/jdownloader:0.7.2-arm64v8` as you always did

**Comment by AndreSDUS** [comment]
okay. i was confused. caus there was no 0.7.2 on docker hub

latest 205 MB
Last update: a day ago
0.7.1-i386 82 MB
Last update: a month ago
0.7.1-armhf 89 MB
Last update: a month ago
0.7.1-arm64v8 79 MB
Last update: a month ago
0.7.1-arm32v6 205 MB
Last update: a month ago
0.7.1-amd64 82 MB
Last update: a month ago

i'll do it again. just a moment...

**Comment by AndreSDUS** [comment]
> --name jd jaymoulin/jdownloader:0.7.2-arm64v8
Unable to find image 'jaymoulin/jdownloader:0.7.2-arm64v8' locally
docker: Error response from daemon: manifest for jaymoulin/jdownloader:0.7.2-arm64v8 not found.

**Comment by jaymoulin** [comment]
@AndreSDUS My bad. Error at upload. available in few minutes

**Comment by AndreSDUS** [comment]
[ce_docker_04_120419.log](https://github.com/jaymoulin/docker-jdownloader/files/3358855/ce_docker_04_120419.log)

new image

**Comment by jaymoulin** [comment]
Still think there's a problem in JDownloader. Even spawned processes just die. cc @jiaz83

**Comment by jiaz83** [comment]
@jaymoulin: 
Somehow the log output doesn't match the script? Or am I missing something?
echo "Process stopped" -> process stopped
sleep 15 -> script then sleeps 15 secs
PID=$(cat /opt/JDownloader/JDownloader.pid) -> found PID 33
echo "Waiting for jdownloader to finish PID : ${PID}" -> Waiting for jdownloader to finish PID : 33

and then there is "PID : 9" but that part of the script is at the beginning?!

**Comment by jaymoulin** [comment]
>  New image with a scanning process features (regardless of jdownloader)

@jiaz83 That's why it's not matching the script you have. I tried to check all process launched by java but this doesn't seem to change anything

**Comment by AndreSDUS** [comment]
Hey.

news and any instructions for me?

Kind regards

**Comment by jiaz83** [comment]
Sorry, didn't find time yet to work on this :(

**Comment by njmdietrich** [comment]
Hi, I seem to be having this issue on an Odroid N2 - also ARM64. I actually had tried to run jdownloader without docker on ubuntu on that machine and had the same issue, now I have coreelec and thought I'd give it a try with a docker container, but it didn't change anything. It seems like the problem is with jdownloader, then, and not with your container. The best thing to do now is probably to ask for help in the jdownloader forum?

**Comment by H34dl3ss** [comment]
So you added fix #32 to address my bootloop issue if I understood correct.
I pulled the container and its up again.
Now we will have to wait for updates to come to see if the fix solves the issue.

**Comment by jaymoulin** [comment]
Don't get this "fix" as a correction to your issue but an addition to an eventual future evolution of JDownloader (which will certainly never come if you read through this feed). In brief : Don't expect this commit to fix anything.

**Comment by H34dl3ss** [comment]
I read once again through this feed. I'm willing to help troubleshooting.
Could you please tell me how/where to grab the logs your are talking about?
Maybe the logs directory should also be exported on the host for easier access?

**Comment by lachnerd** [comment]
I'm facing the same error on a RPI 3 b.

**Comment by 3710-sudo** [comment]
Hello
same thing for me also : always restarting : i'm on Libreelec 9.0.2 running on wetek play 2 (aarch64)
i'm noob but if i can help someone...

**Comment by jaymoulin** [comment]
Still not able to reproduce this issue on a Rpi 3b.

Can you check you have similar values to those commands:

```
$> uname -m
aarch64
$> docker --version
Docker version 19.03.3 build a872fc2
```

**Comment by jaymoulin** [comment]
Just tested this on LibreElec + RaspberryPI 3b+ and everything went OK:

```
LibreELEC:~ # uname -a
Linux LibreELEC 4.19.83 #1 SMP Sat Nov 23 01:55:35 CET 2019 armv7l GNU/Linux
LibreELEC:~ # uname -m
armv7l
LibreELEC:~ # docker --version
Docker version 18.09.7, build 18.09.7
LibreELEC:~ # docker inspect jaymoulin/jdownloader | grep version
                "version": "1.0.0-armhf"
                "version": "1.0.0-armhf"
```

All test I ever done on all images are working. Nothing more could be done here.
