### ISSUE TITLE
Jdownloader automatically shutdown 

### ISSUE THREAD

**Issue by faberix76** [jaymoulin/docker-jdownloader#35]
Hello, i've an issue with your container. It seems to automatically shutdown and the continer doesn't keep running:

<details>
<pre>
THREAD: 16
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:16 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Test
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:16 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Running

THREAD: 50
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:16 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] ->
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:16 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> THREAD: 17
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:16 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 17|Log.L.log 8/25/19 7:59:16 AM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/tmp/update/self/JDU/cfg/org.jdownloader.settings.InternetConnectionSettings.customproxylist.json

THREAD: 51
51|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:16 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> UpdateClient Proxy Vole 29

THREAD: 50
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 17|Log.L.log 8/25/19 7:59:17 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Translation file missing:org/appwork/utils/locale/AWUTranslation.en.lngUse Annotation Dev fallback
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] ->
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> THREAD: 17
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 17|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> GET http://update.appwork.org/jcgi/lastchance?app=JD&pkh=12f1848a883e733ed40fffff0dae2f35&jh=695e589ed7f6e3c4a90152b0176bbdae&rev=-1&srev=-1&urev=-1&surev=-1&rt=ST&st=1 via [Direct]
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 17|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(internalDownloadWithProxy) ] -> Try Proxy: Direct
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 17|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Download to /tmp/lastChanceSrc15667199567906839376236849307758lch Size before: 0 bytes
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 17|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Connection:
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> ----------------Request Information-------------
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> URL: http://cdn4.appwork.org/JD/JD_lastChanceRescueMe.jar.enc
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> ConnectIP: cdn4.appwork.org/176.9.34.43:80
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Connection-Timeout: 20000ms
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Read-Timeout: 60000ms
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> ----------------Request-------------------------
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> GET /JD/JD_lastChanceRescueMe.jar.enc HTTP/1.1
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Host: cdn4.appwork.org
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Accept-Language: en_US
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> User-Agent: JDownloader/201707061810
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Cache-Control: no-cache, no-store
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Pragma: no-cache
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Connection: Close
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> ----------------Response Information------------
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Connection-Time: 39ms
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Request-Time: 51ms
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> ----------------Response------------------------
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> HTTP/1.1 200 OK
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Server: nginx/1.15.12
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Date: Sun, 25 Aug 2019 07:59:17 GMT
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Content-Type: application/octet-stream
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Content-Length: 1696
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Last-Modified: Wed, 03 Apr 2013 12:41:08 GMT
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Connection: close
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> ETag: "515c2364-6a0"
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> X-CDN: 76_0_6_70
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> X-CDN-SIGNATURE: .Nanachi.
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> Accept-Ranges: bytes
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> ------------------------------------------------
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] ->
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] ->
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 17|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Connection ok. Downloaded /tmp/lastChanceSrc15667199567906839376236849307758lch: 1696 bytes

THREAD: 16
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Test
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:17 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Running

THREAD: 50
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:18 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] ->
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:18 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> THREAD: 1
50|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:18 AM - INFO [ org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString) ] -> 1|org.jdownloader.update.launcher.SelfTest.log 8/25/19 7:59:18 AM - INFO [ org.jdownloader.update.launcher.SelfTest(onSelfTestOK) ] -> Write PollFile: /opt/JDownloader/tmp/selftest_1566719954773

THREAD: 16
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:18 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Test
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:18 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> Running
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:18 AM - INFO [ org.jdownloader.update.SelfUpdateClient(finishSelfUpdate) ] -> File exists
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:20 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> Validate:  OK
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:20 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> SelfTest Results:
OK
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:20 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> OK
16|org.jdownloader.update.UpdateManager.log 8/25/19 7:59:20 AM - INFO [ org.jdownloader.update.SelfUpdateClient(validateSelfTestFile) ] -> Self Update successful
16|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:20 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> Request Shutdown: org.jdownloader.updatev2.SmartRlyExitRequest@bd0ef8
16|Log.L.log 8/25/19 7:59:20 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> No Vetos
16|Log.L.log 8/25/19 7:59:20 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Fire onShutDownEvents
16|Log.L.log 8/25/19 7:59:20 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Create ExitThread
16|Log.L.log 8/25/19 7:59:20 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Wait

THREAD: 53
53|Log.L.log 8/25/19 7:59:20 AM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Exit Now: Code: 0

THREAD: 8
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:20 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/7|Priority: 10000]ShutdownController: start item->ShutdownRunableEvent Priority: 10000
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:20 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/7|Priority: 10000]ShutdownController: item ended after->3
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:20 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:1/7]
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:20 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/7|Priority: 10000]ShutdownController: start item->flushing logs to disk
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/7|Priority: 10000]ShutdownController: item ended after->143
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:2/7]
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/7|Priority: 0]ShutdownController: start item->ShutdownEvent: Save JSonStorages

THREAD: 56
56|Log.L.log 8/25/19 7:59:21 AM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Start Saving Storage
56|Log.L.log 8/25/19 7:59:21 AM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> ENDED Saving Storage
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/7|Priority: 0]ShutdownController: item ended after->2
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:3/7]
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/7|Priority: 0]ShutdownController: start item->ShutdownEvent: SaveAllStorageHandler
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/7|Priority: 0]ShutdownController: item ended after->10
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:4/7]
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/7|Priority: 0]ShutdownController: start item->ShutdownEvent: ProcessDelayedWrites num=0
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/7|Priority: 0]ShutdownController: item ended after->2
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:5/7]
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/7|Priority: -2147483648]ShutdownController: start item-> Priority: -2147483648
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/7|Priority: -2147483648]ShutdownController: item ended after->2
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:6/7]
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/7|Priority: -2147483648]ShutdownController: start item->ShutdownEventWrapper Thread[Thread-0,5,main] - java.util.logging.LogManager$Cleaner Priority: -2147483648
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/7|Priority: -2147483648]ShutdownController: item ended after->2
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:7/7]
8|org.appwork.shutdown.ShutdownController.log 8/25/19 7:59:21 AM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> Shutdown Hooks Finished
</details>
</pre>

As you can see, there is nothing i can do to make it runnig, it close itself automatically. I'm on an RPI4 with the latest raspbian and docker version 19.03.1, build 74b1e89.

Best Regards,
Fabio

**Comment by jaymoulin** [comment]
The issue doesn't match the required template for issues. Please complete so I can be sure all your steps were done correctly. Lacking those information, the issue will be closed
