### ISSUE TITLE
jdownloader runs into bootloop after update

### ISSUE THREAD

**Issue by H34dl3ss** [jaymoulin/docker-jdownloader#39]
Hi,
I've been running the 32bit docker on the RPi now for a while until
it happened. After an update the instance didn't came back on screen in myjdownloader.
I checked the docker and the container was stopped.
Restarting didn't bring it back either.
I decided to pull the docker again and it worked.
Also the subsequent update ran OK and I was good again.

Yesterday I started another update via myjdownloader - there are really frequent updates, and it happened again, the docker didn't come back online.
I checked the status via commandline and it showed the docker was shutdown.
After starting it again, it is running for about 60 sec. and then it seems to crash.

Could you please help me solve this issue?
I'm not very familiar with docker. While it is very comfortable to use dockers,
troubleshooting is a bit more complicated now.
What do you need, and how can I extract it from the docker.

I could also upload the whole container for you if that's possible.
Just need some instructions how to do that.

**Comment by jaymoulin** [comment]
duplicate #32
