### ISSUE TITLE
Running as non-root user

### ISSUE THREAD

**Issue by barbudor** [jaymoulin/docker-jdownloader#40]
Hi
It works but it took me some time to figure out the right way so I suggest a slight update to the README.

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**
`1.0.0-amd64`

**Description**

I had some difficulties to move from a fully working setup under the root account to a setup working under an non-root user.

**Command line I used to start the container**
Under account `user1`, member of `docker` group I ran the command line as given in your README:
`docker run -d --init --restart=always -v /home/user1/jd/downloads:/roots/Downloads -v /home/user1/jd/logs:/opt/JDownloader/logs -v /home/user1/jd/cfg:/opt/JDownloader/cfg --name jdownloader -u $(id -u):$(id -g) jaymoulin/jdownloader` 

**Steps to reproduce the issue:**
**Describe the results you received:**

Downloads to `/root/Downloads` (to match your README command line) fails with directory invalid. This is due to user not haveing the write access to `/root`  in the container (despite he has on the host folder `/home/user1/jd/downloads`).

**Fixing:**

Changing the target of the volume for downloads as `/opt/JDownloader/Downloads` fix the problem:
`-v /home/user1/jd/downloads:/opt/JDownloader/Downloads`

**Suggestion**

I suggest to ammend the README to recommend mounting the download volume to `/opt/JDownloader/Downloads` instead of `/root/Downloads`.

Note that I also found a reference to `/root/Downloads` on line 9 of `daemon.sh` which may also need to be updated to `/opt/JDownloader/downloads` for safety.

Thanks a lot.
Cordialement

**Comment by jaymoulin** [comment]
Thank you for reporting this.
If you find this product useful, please consider donation to help me continue making/creating great products (eg. https://patreon.com/femtopixel)
