### ISSUE TITLE
How to configure the device name?

### ISSUE THREAD

**Issue by xong** [jaymoulin/docker-jdownloader#43]
Hi,

thank you for this docker image.

Is there a way to configure the device name, so the JDownloader account can be used by multiple devices?
At the Windows-GUI you can configure the `Device Name` with the account data (ignore the errors, I just found this picture with Google): ![Image of Yaktocat](https://webspace.appwork.org/JDownloader_2_BETA_2015-02-14_19-40-08.png)

Regards
Robert

**Comment by jaymoulin** [comment]
Hello Robert,

Thank you for your interest in this product. If you find this useful, please consider making donation.

On MyJdownloader (https://my.jdownloader.org/), choose an instance then go to **Settings > Advanced Settings**
Then, search for **device name** in the filter box and change the value to whatever suits you.
