### ISSUE TITLE
"Image": "jaymoulin/jdownloader:latest" fails to start on 1.0.1-armhf

### ISSUE THREAD

**Issue by olosz** [jaymoulin/docker-jdownloader#44]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
1.0.1-armhf
```

Docker image restarts and at some point fails to start. Started like week ago.

**Command line I used to start the container**
OpenMediaVault Docker does it for me. Followed the TechnoDad tutorial on YouTube.

**Steps to reproduce the issue:**
1. Restart the container

**Describe the results you received:**
Log.L.log 1/31/20 2:37:55 PM - SEVERE [ Log.L.log ] -> Exception thrown at jd.SecondLevelLaunch$10$1.run(SecondLevelLaunch.java:956):
java.lang.ExceptionInInitializerError
	at jd.SecondLevelLaunch$10$1.run(SecondLevelLaunch.java:784)
Caused by: java.lang.RuntimeException: No Console Available!
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:118)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:107)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:32)
	... 1 more

**Describe the results you expected:**
Start the image, be able to log in. Now it says 'No connected JDownloader found' 

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue started like week ago. I see watchtower has updated and pulled the image then.

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
27|Log.L.log 1/31/20 2:37:55 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /dialogs = interface org.jdownloader.api.dialog.DialogApiInterface
27|Log.L.log 1/31/20 2:37:55 PM - SEVERE [ Log.L.log ] -> Exception thrown at jd.SecondLevelLaunch$10$1.run(SecondLevelLaunch.java:956):
java.lang.ExceptionInInitializerError
        at jd.SecondLevelLaunch$10$1.run(SecondLevelLaunch.java:784)
Caused by: java.lang.RuntimeException: No Console Available!
        at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
        at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
        at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:118)
        at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:107)
        at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:32)
        ... 1 more

Start Update
Update Message: Check for updates
Update Progress: 3%
Update Progress: -1%
Update Message: Contact Server...
Update Message: Check for updates
</pre>
</details>

**Comment by jaymoulin** [comment]
Thank you for your interest in this repository. If you find this product useful, please consider donation.

Looks like you forgot to add your credentials to be able to connect
https://youtu.be/l-c9cozu5vw?t=217

Let me know

**Comment by olosz** [comment]
Thank you for your feedback.
Passing the credentials again did not make a change. Same issue occurs.
Please note the container has been running successfully for months.

**Comment by jaymoulin** [comment]
Unless you deleted your container OR made an explicite updte (I don't know how OVM works, neither if it updates its images), the image can't be responsible for a breaking container if it was already running.

The given exception is a JDownloader specific error that tries to display an information in a non existing console (which should not be available without `-t` parameter) and should occur in an headless system.

If you saved your settings folder (as recommended in README), you should be able to delete/recreate your container to force your new container to redownload its JDownloader executable.

You can also use the debug feature by adding a `jdownloader-block.txt` in your download folder and try this command "docker exec jdownloader rm  /opt/JDownloader/JDownloader.jar" to force the container to redownload its JDownloader executable.

**Comment by olosz** [comment]
The executable has been re-downloaded but ends with the same error.
I recreated the container but no results - the same error.
Shall I start from scratch and rm the configuration folder first?

**Comment by jaymoulin** [comment]
Yes, you can try with removing your configuration folder. This may solve your issue.

I suggest you pass the `-t` parameter when you'll recreate your container to give JDownloader a terminal for it to be able to print what it wants to.

**Comment by olosz** [comment]
Removing the folders and starting from scratch, resolved the issue. Thank you.
