### ISSUE TITLE
container start-up error ( A fatal error has been detected by the Java Runtime Environment )

### ISSUE THREAD

**Issue by BelphegorPrime** [jaymoulin/docker-jdownloader#52]
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
1.3.0-amd64
```

**Description**

**Command line I used to start the container**
docker-compose up -d

with the following docker-compose.yml file

<details>
<pre>
version: "3"
services:
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader-latest
    user: "1000:1000"
    ports:
      - 3129:3129
    volumes:
      - /path/to/config:/opt/JDownloader/cfg
      - /path/to/downloads:/opt/JDownloader/Downloads
    restart: unless-stopped
</pre>
</details

**Steps to reproduce the issue:**
1. 1.2.0 works well
2. update to 1.3.0 causes errors. Take a look at the appended log file

**Describe the results you received:**
Container fails to start-up

**Describe the results you expected:**
Container starts as expected

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
--2020-03-13 21:22:03--  http://installer.jdownloader.org/JDownloader.jar?32351,
Resolving installer.jdownloader.org... 85.131.130.148,
Connecting to installer.jdownloader.org|85.131.130.148|:80... connected.,
HTTP request sent, awaiting response... 200 OK,
Length: 3565926 (3.4M) [application/octet-stream],
Saving to: '/opt/JDownloader/JDownloader.jar',
,
     0K .......... .......... .......... .......... ..........  1%  931K 4s,
    50K .......... .......... .......... .......... ..........  2% 2.18M 3s,
   100K .......... .......... .......... .......... ..........  4% 1.70M 2s,
   150K .......... .......... .......... .......... ..........  5% 2.93M 2s,
   200K .......... .......... .......... .......... ..........  7% 3.02M 2s,
   250K .......... .......... .......... .......... ..........  8% 2.50M 2s,
   300K .......... .......... .......... .......... .......... 10% 2.04M 2s,
   350K .......... .......... .......... .......... .......... 11% 2.84M 2s,
   400K .......... .......... .......... .......... .......... 12% 2.77M 1s,
   450K .......... .......... .......... .......... .......... 14% 2.81M 1s,
   500K .......... .......... .......... .......... .......... 15% 4.89M 1s,
   550K .......... .......... .......... .......... .......... 17% 28.3M 1s,
   600K .......... .......... .......... .......... .......... 18% 20.5M 1s,
   650K .......... .......... .......... .......... .......... 20% 5.04M 1s,
   700K .......... .......... .......... .......... .......... 21% 4.13M 1s,
   750K .......... .......... .......... .......... .......... 22% 6.16M 1s,
   800K .......... .......... .......... .......... .......... 24% 5.31M 1s,
   850K .......... .......... .......... .......... .......... 25% 6.03M 1s,
   900K .......... .......... .......... .......... .......... 27% 6.14M 1s,
   950K .......... .......... .......... .......... .......... 28% 5.22M 1s,
  1000K .......... .......... .......... .......... .......... 30% 6.31M 1s,
  1050K .......... .......... .......... .......... .......... 31% 5.12M 1s,
  1100K .......... .......... .......... .......... .......... 33% 5.96M 1s,
  1150K .......... .......... .......... .......... .......... 34% 5.38M 1s,
  1200K .......... .......... .......... .......... .......... 35% 5.80M 1s,
  1250K .......... .......... .......... .......... .......... 37% 5.61M 1s,
  1300K .......... .......... .......... .......... .......... 38% 5.86M 1s,
  1350K .......... .......... .......... .......... .......... 40% 5.95M 1s,
  1400K .......... .......... .......... .......... .......... 41% 5.61M 1s,
  1450K .......... .......... .......... .......... .......... 43% 6.13M 1s,
  1500K .......... .......... .......... .......... .......... 44% 5.53M 1s,
  1550K .......... .......... .......... .......... .......... 45% 5.92M 0s,
  1600K .......... .......... .......... .......... .......... 47% 5.71M 0s,
  1650K .......... .......... .......... .......... .......... 48% 5.93M 0s,
  1700K .......... .......... .......... .......... .......... 50% 5.77M 0s,
  1750K .......... .......... .......... .......... .......... 51% 5.70M 0s,
  1800K .......... .......... .......... .......... .......... 53% 6.13M 0s,
  1850K .......... .......... .......... .......... .......... 54% 5.46M 0s,
  1900K .......... .......... .......... .......... .......... 55% 6.13M 0s,
  1950K .......... .......... .......... .......... .......... 57% 5.98M 0s,
  2000K .......... .......... .......... .......... .......... 58% 5.47M 0s,
  2050K .......... .......... .......... .......... .......... 60% 5.10M 0s,
  2100K .......... .......... .......... .......... .......... 61% 5.84M 0s,
  2150K .......... .......... .......... .......... .......... 63% 6.32M 0s,
  2200K .......... .......... .......... .......... .......... 64% 5.33M 0s,
  2250K .......... .......... .......... .......... .......... 66% 5.98M 0s,
  2300K .......... .......... .......... .......... .......... 67% 5.84M 0s,
  2350K .......... .......... .......... .......... .......... 68% 5.59M 0s,
  2400K .......... .......... .......... .......... .......... 70% 6.14M 0s,
  2450K .......... .......... .......... .......... .......... 71% 5.81M 0s,
  2500K .......... .......... .......... .......... .......... 73% 5.48M 0s,
  2550K .......... .......... .......... .......... .......... 74% 5.83M 0s,
  2600K .......... .......... .......... .......... .......... 76% 6.12M 0s,
  2650K .......... .......... .......... .......... .......... 77% 5.62M 0s,
  2700K .......... .......... .......... .......... .......... 78% 5.81M 0s,
  2750K .......... .......... .......... .......... .......... 80% 5.98M 0s,
  2800K .......... .......... .......... .......... .......... 81% 5.63M 0s,
  2850K .......... .......... .......... .......... .......... 83% 5.66M 0s,
  2900K .......... .......... .......... .......... .......... 84% 6.14M 0s,
  2950K .......... .......... .......... .......... .......... 86% 5.63M 0s,
  3000K .......... .......... .......... .......... .......... 87% 5.53M 0s,
  3050K .......... .......... .......... .......... .......... 89% 6.16M 0s,
  3100K .......... .......... .......... .......... .......... 90% 5.59M 0s,
  3150K .......... .......... .......... .......... .......... 91% 5.96M 0s,
  3200K .......... .......... .......... .......... .......... 93% 5.83M 0s,
  3250K .......... .......... .......... .......... .......... 94% 5.77M 0s,
  3300K .......... .......... .......... .......... .......... 96% 5.82M 0s,
  3350K .......... .......... .......... .......... .......... 97% 5.95M 0s,
  3400K .......... .......... .......... .......... .......... 99% 5.64M 0s,
  3450K .......... .......... .......... ..                   100% 5.24M=0.7s,
,
2020-03-13 21:22:04 (4.65 MB/s) - '/opt/JDownloader/JDownloader.jar' saved [3565926/3565926],
,
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory,
java.lang.NoClassDefFoundError: sun/misc/Launcher,
	at org.appwork.utils.JarHandlerWorkaroundOracle.init(JarHandlerWorkaroundOracle.java:72),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:567),
	at org.appwork.utils.JarHandlerWorkaround.init(JarHandlerWorkaround.java:56),
	at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:9),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:567),
	at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:63),
Caused by: java.lang.ClassNotFoundException: sun.misc.Launcher,
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436),
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588),
	at org.jdownloader.update.launcher.JDLauncher$JDLauncherClassLoader.loadClass(JDLauncher.java:27),
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521),
	... 12 more,
WARNING: An illegal reflective access operation has occurred,
WARNING: Illegal reflective access by org.appwork.shutdown.ShutdownController (file:/opt/JDownloader/JDownloader.jar) to field java.lang.ApplicationShutdownHooks.hooks,
WARNING: Please consider reporting this to the maintainers of org.appwork.shutdown.ShutdownController,
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations,
WARNING: All illegal access operations will be denied in a future release,
sun.Desktop: null,
XDG_CURRENT_DESKTOP: null,
KDE_FULL_SESSION: null,
KDE_SESSION_VERSION: null,
DESKTOP_SESSION: null,
GNOME_DESKTOP_SESSION_ID: null,
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json,
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig,
#,
# A fatal error has been detected by the Java Runtime Environment:,
#,
#  SIGSEGV (0xb) at pc=0x00007fa10ab26d11, pid=30, tid=47,
#,
# JRE version: OpenJDK Runtime Environment (13.0.2+9) (build 13.0.2+9),
# Java VM: OpenJDK 64-Bit Server VM (13.0.2+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64),
# Problematic frame:,
# C  [libc.so.6+0x119d11],
#,
# Core dump will be written. Default location: /opt/JDownloader/core,
#,
# An error report file with more information is saved as:,
# /opt/JDownloader/hs_err_pid30.log,
,,
1,
1|Log.L.log 3/13/20, 9:22:05 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Application Root: /opt/JDownloader,
#,
# If you would like to submit a bug report, please visit:,
#   http://bugreport.java.com/bugreport/crash.jsp,
#,
JarHandlerWorkaroundOracle:setURLStreamHandlerFactory,
java.lang.NoClassDefFoundError: sun/misc/Launcher,
	at org.appwork.utils.JarHandlerWorkaroundOracle.init(JarHandlerWorkaroundOracle.java:72),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:567),
	at org.appwork.utils.JarHandlerWorkaround.init(JarHandlerWorkaround.java:56),
	at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:9),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:567),
	at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:63),
Caused by: java.lang.ClassNotFoundException: sun.misc.Launcher,
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436),
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588),
	at org.jdownloader.update.launcher.JDLauncher$JDLauncherClassLoader.loadClass(JDLauncher.java:27),
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521),
	... 12 more,
WARNING: An illegal reflective access operation has occurred,
WARNING: Illegal reflective access by org.appwork.shutdown.ShutdownController (file:/opt/JDownloader/JDownloader.jar) to field java.lang.ApplicationShutdownHooks.hooks,
WARNING: Please consider reporting this to the maintainers of org.appwork.shutdown.ShutdownController,
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations,
WARNING: All illegal access operations will be denied in a future release,
sun.Desktop: null,
XDG_CURRENT_DESKTOP: null,
KDE_FULL_SESSION: null,
KDE_SESSION_VERSION: null,
DESKTOP_SESSION: null,
GNOME_DESKTOP_SESSION_ID: null,
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json,
FINER >> Init StorageHandler for Interface:org.appwork.utils.logging2.LogConfig|Path:/opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig,
#,
# A fatal error has been detected by the Java Runtime Environment:,
#,
#  SIGSEGV (0xb) at pc=0x00007f05ef385d11, pid=27, tid=45,
#,
# JRE version: OpenJDK Runtime Environment (13.0.2+9) (build 13.0.2+9),
# Java VM: OpenJDK 64-Bit Server VM (13.0.2+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64),
# Problematic frame:,
# C  [libc.so.6+0x119d11],
#,
# Core dump will be written. Default location: /opt/JDownloader/core,
#,
# An error report file with more information is saved as:,
# /opt/JDownloader/hs_err_pid27.log,
,,
1,
1|Log.L.log 3/13/20, 9:22:19 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Application Root: /opt/JDownloader,
#,
# If you would like to submit a bug report, please visit:,
#   http://bugreport.java.com/bugreport/crash.jsp,
#,
</pre>
</details>

**Comment by SadButTrueAT** [comment]
im having exactly the same problem.

i`m back at using 1.2.0 again without problems.

**Comment by MagmaMDK** [comment]
Same problem here on synology docker

**Comment by jaymoulin** [comment]
resolved by rollback

**Comment by jaymoulin** [comment]
If like to remind giving donation will help me fix the problems and maintaining this product :
[![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin)
[![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W)
[![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin)

**Comment by jaymoulin** [comment]
Confirmation this is resolved: https://github.com/jaymoulin/docker-jdownloader/issues/49#issuecomment-599281784

Thanks to Thomas Presier for his donation
