### ISSUE TITLE
Reboot loop on OMV docker - java not found

### ISSUE THREAD

**Issue by ChriKn** [jaymoulin/docker-jdownloader#54]
Hi there,

since my last attempt to connect to myjdownloader, sadly the container seems broken...
I am using OMV on an odroid HC2, everything is updated.

I allready tried :
- relaunching the whole image / container
- deleting the config folder

Apparently the image was updated some days ago, this is the only major change in my system.
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
1.3.0-armhf
```

**Description**

**Command line I used to start the container**
OMV GUIs "start" command

**Steps to reproduce the issue:**
1.start the container

**Provide some logs (`docker logs jdownloader`)**

<details><pre>
--2020-03-15 16:21:43--  http://installer.jdownloader.org/JDownloader.jar?32540
Resolving installer.jdownloader.org... 85.131.130.148
Connecting to installer.jdownloader.org|85.131.130.148|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3565926 (3.4M) [application/octet-stream]
Saving to: '/opt/JDownloader/JDownloader.jar'

     0K .......... .......... .......... .......... ..........  1% 1.92M 2s
    50K .......... .......... .......... .......... ..........  2% 4.21M 1s
   100K .......... .......... .......... .......... ..........  4% 10.4M 1s
   150K .......... .......... .......... .......... ..........  5% 11.1M 1s
   200K .......... .......... .......... .......... ..........  7% 7.16M 1s
   250K .......... .......... .......... .......... ..........  8% 11.5M 1s
   300K .......... .......... .......... .......... .......... 10% 11.0M 1s
   350K .......... .......... .......... .......... .......... 11% 10.9M 1s
   400K .......... .......... .......... .......... .......... 12% 11.1M 0s
   450K .......... .......... .......... .......... .......... 14% 11.5M 0s
   500K .......... .......... .......... .......... .......... 15% 11.1M 0s
   550K .......... .......... .......... .......... .......... 17% 10.9M 0s
   600K .......... .......... .......... .......... .......... 18% 11.1M 0s
   650K .......... .......... .......... .......... .......... 20% 11.6M 0s
   700K .......... .......... .......... .......... .......... 21% 11.1M 0s
   750K .......... .......... .......... .......... .......... 22% 11.0M 0s
   800K .......... .......... .......... .......... .......... 24% 11.1M 0s
   850K .......... .......... .......... .......... .......... 25% 11.0M 0s
   900K .......... .......... .......... .......... .......... 27% 11.6M 0s
   950K .......... .......... .......... .......... .......... 28% 11.0M 0s
  1000K .......... .......... .......... .......... .......... 30% 11.0M 0s
  1050K .......... .......... .......... .......... .......... 31% 11.1M 0s
  1100K .......... .......... .......... .......... .......... 33% 11.6M 0s
  1150K .......... .......... .......... .......... .......... 34% 11.0M 0s
  1200K .......... .......... .......... .......... .......... 35% 10.9M 0s
  1250K .......... .......... .......... .......... .......... 37% 11.2M 0s
  1300K .......... .......... .......... .......... .......... 38% 11.0M 0s
  1350K .......... .......... .......... .......... .......... 40% 11.7M 0s
  1400K .......... .......... .......... .......... .......... 41% 2.54M 0s
  1450K .......... .......... .......... .......... .......... 43% 20.8M 0s
  1500K .......... .......... .......... .......... .......... 44% 24.2M 0s
  1550K .......... .......... .......... .......... .......... 45% 24.6M 0s
  1600K .......... .......... .......... .......... .......... 47% 23.3M 0s
  1650K .......... .......... .......... .......... .......... 48% 20.1M 0s
  1700K .......... .......... .......... .......... .......... 50% 22.1M 0s
  1750K .......... .......... .......... .......... .......... 51% 16.6M 0s
  1800K .......... .......... .......... .......... .......... 53% 11.3M 0s
  1850K .......... .......... .......... .......... .......... 54% 11.3M 0s
  1900K .......... .......... .......... .......... .......... 55% 11.3M 0s
  1950K .......... .......... .......... .......... .......... 57% 11.0M 0s
  2000K .......... .......... .......... .......... .......... 58% 10.7M 0s
  2050K .......... .......... .......... .......... .......... 60% 11.6M 0s
  2100K .......... .......... .......... .......... .......... 61% 11.0M 0s
  2150K .......... .......... .......... .......... .......... 63% 11.1M 0s
  2200K .......... .......... .......... .......... .......... 64% 11.0M 0s
  2250K .......... .......... .......... .......... .......... 66% 11.0M 0s
  2300K .......... .......... .......... .......... .......... 67% 11.8M 0s
  2350K .......... .......... .......... .......... .......... 68% 11.1M 0s
  2400K .......... .......... .......... .......... .......... 70% 10.9M 0s
  2450K .......... .......... .......... .......... .......... 71% 11.0M 0s
  2500K .......... .......... .......... .......... .......... 73% 11.7M 0s
  2550K .......... .......... .......... .......... .......... 74% 10.9M 0s
  2600K .......... .......... .......... .......... .......... 76% 11.1M 0s
  2650K .......... .......... .......... .......... .......... 77% 10.9M 0s
  2700K .......... .......... .......... .......... .......... 78% 11.2M 0s
  2750K .......... .......... .......... .......... .......... 80% 11.7M 0s
  2800K .......... .......... .......... .......... .......... 81% 10.9M 0s
  2850K .......... .......... .......... .......... .......... 83% 11.2M 0s
  2900K .......... .......... .......... .......... .......... 84% 10.9M 0s
  2950K .......... .......... .......... .......... .......... 86% 11.5M 0s
  3000K .......... .......... .......... .......... .......... 87% 11.0M 0s
  3050K .......... .......... .......... .......... .......... 89% 10.9M 0s
  3100K .......... .......... .......... .......... .......... 90% 11.7M 0s
  3150K .......... .......... .......... .......... .......... 91% 10.9M 0s
  3200K .......... .......... .......... .......... .......... 93% 11.0M 0s
  3250K .......... .......... .......... .......... .......... 94% 11.3M 0s
  3300K .......... .......... .......... .......... .......... 96% 11.3M 0s
  3350K .......... .......... .......... .......... .......... 97% 11.1M 0s
  3400K .......... .......... .......... .......... .......... 99% 11.2M 0s
  3450K .......... .......... .......... ..                   100% 11.5M=0.3s

2020-03-15 16:21:43 (10.1 MB/s) - '/opt/JDownloader/JDownloader.jar' saved [3565926/3565926]

/opt/JDownloader/daemon.sh: line 34: java: not found</pre></details>

**Comment by jaymoulin** [comment]
This issue is a residue of the prior 1.3.0 version. This should be fixed now.

You need to pull the latest image and recreate your container to be able to use the fix.

If you find this product useful, please consider donation to help me continue maintain and create great products [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/femtopixel))

**Comment by ChriKn** [comment]
Worked, thank you !
