### ISSUE TITLE
1.3.0 java not found

### ISSUE THREAD

**Issue by SadButTrueAT** [jaymoulin/docker-jdownloader#55]
tested your just releasd 1.3.0 again and now i have another error:

2020-03-15 17:32:20 (9.77 MB/s) - '/opt/JDownloader/JDownloader.jar' saved [3565926/3565926]
/opt/JDownloader/daemon.sh: line 38: java: not found

**Comment by jaymoulin** [comment]
This issue doesn't match prerequisites. Closed for nothing can be done here
