### ISSUE TITLE
Build on top of newer images

### ISSUE THREAD

**Issue by darkdragon-001** [jaymoulin/docker-jdownloader#57]
It seems that `openjdk:jre-alpine` is no longer updated (since 2 years). I couldn't find any `alpine` tag without explicitly specifying the OpenJDK version though. I tested with `openjdk:15-alpine` successfully. OpenJDK 12+ needs to install the package `fontconfig` as done in the official images (not alpine builds though): https://github.com/caodianlong/openjdk/blob/master/11/jdk/oracle/Dockerfile#L10

**Comment by jaymoulin** [comment]
Thank you for your suggestion. Why do you need this?

**Comment by darkdragon-001** [comment]
`openjdk:jre-alpine` doesn't seem to be updated any more. Thus existing security vulnerabilities (e.g. in the `alpine` image used as base) are not fixed and will be present in the final image.

**Comment by darkdragon-001** [comment]
Btw: installation of `fontconfig` package is not needed any more in the latest version.

**Comment by jaymoulin** [comment]
For information purpose (explained in the linked PR).
>  I specified a deprecated JDK version because the latest version is not compatible with all architectures and causes segfaults (#52, #54, #55, #56)
