### ISSUE TITLE
Dockerfile: "FROM builder" without any effect

### ISSUE THREAD

**Issue by darkdragon-001** [jaymoulin/docker-jdownloader#59]
https://github.com/jaymoulin/docker-jdownloader/blob/a728c4409d202ad08d6c26ffc8089a390cbfefe0/Dockerfile#L6

This doesn't have any effect as stated in the [documentation](https://docs.docker.com/develop/develop-images/multistage-build/#use-a-previous-stage-as-a-new-stage):

> You can pick up where a previous stage left off by referring to it when using the FROM directive.

**Comment by jaymoulin** [comment]
Thank you for reporting this. I know that this line is useless for now. I anticipated this to be able to build images without needing to add qemu in the images (which I am not able to achieve yet as the buildx method removes useful features)

If you find this product useful, please consider donation to help me continue maintain and create great products ([![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin))
