### ISSUE TITLE
Update Jdownloader

### ISSUE THREAD

**Issue by Lunqtic** [jaymoulin/docker-jdownloader#65]
Hello,

There has been a lot of modification on Jdownloader 2 I wanted to know if the updates are automatic on the website or do you have to do an update on the docker? 

Thank you

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

The JDownloader core software implemented in this docker image do not need to be updated. Nevertheless, updates are performed on container creation (first time you launched the docker command with this image).

All new update for your actual container can be performed on your MyJDownloader interface (Settings > Update and restard JD Button). This will reboot your container with the latest updates. An integrated security is triggered in the event of an error to install an updated instance.
