### ISSUE TITLE
Container auto shutdown on RPi4

### ISSUE THREAD

**Issue by Sulfkain** [jaymoulin/docker-jdownloader#68]
**Description**
I'm using your container in a Raspberry Pi 4 with raspbian buster 10.3 with Kernel 4.19.97 (latest)
I'm using [OMV](https://www.openmediavault.org/) version 5.4.2-1(Usul) (latest)
Docker version 5:19.03.8~3-0~debian-buster
with Portainer v19.03.8

I configured and start it, but after some seconds it auto shutdown with this log.

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**
```
1.3.1-armhf
```

**Command line I used to start the container**
It's runs with out any command line, just pointing to "CMD | /opt/JDownloader/daemon.sh"
with ENTRYPOINT = null (I don't know if this is usefull)

**Steps to reproduce the issue:**
1. Add "jaymoulin/jdownloader:latest"
2. And deploy the container

**Describe the results you received:**
I start the container and almost immediately it auto shutdown

**Describe the results you expected:**
I expected, the container still live.

**Additional information you deem important (e.g. issue happens only occasionally):**
There was another issue pretty similar if not the same, but was closed due structured info, so I tried to explain and add more info about it.
https://github.com/jaymoulin/docker-jdownloader/issues/35

**Provide some logs (`docker logs jdownloader`)**

The first part is installation and update
On the last lines (20 lines circa) it's where shutdown happens

<details>
<pre>
Date: Fri, 01 May 2020 09:22:42 GMT
,
Content-Type: text/plain; charset=UTF-8
,
Content-Length: 2
,
Connection: close
,
Server: AppWork GmbH FcgiServer
,
JCGI: 1
,
UPD_SRV: 1
,
------------------------------------------------
,
,
Update Progress: 28.041%,
Update Message: Download Updates...
,
Downloadspeed: 4.28 MB/s, Time left: 57s,
Update Progress: 28.074%,
Update Message: Download Updates...
,
Downloadspeed: 4.28 MB/s, Time left: 01m:04s,
Update Progress: 28.101%,
Update Message: Download Updates...
,
Downloadspeed: 4.28 MB/s, Time left: 01m:10s,
Update Progress: 28.135%,
Update Message: Download Updates...
,
Downloadspeed: 4.27 MB/s, Time left: 01m:14s,
Update Progress: 28.309%,
Update Message: Download Updates...
,
Downloadspeed: 4.27 MB/s, Time left: 01m:14s,
Update Progress: 30.434%,
Update Message: Download Updates...
,
Downloadspeed: 4.30 MB/s, Time left: 35s,
Update Progress: 36.928%,
Update Message: Download Updates...
,
Downloadspeed: 4.39 MB/s, Time left: 06s,
,
THREAD: 27,
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Connection:
,
----------------Request Information-------------
,
URL: http://cdn4.appwork.org/JDU/13908/1588265874234dc37ec8a2f9a29f1cd2b61d99e59d19a_094117506f03baa898f0a8de63de8d627eda3d209-0
,
ConnectIP: cdn4.appwork.org/176.9.34.43:80
,
Connection-Timeout: 20000ms
,
Read-Timeout: 60000ms
,
----------------Request-------------------------
,
GET /JDU/13908/1588265874234dc37ec8a2f9a29f1cd2b61d99e59d19a_094117506f03baa898f0a8de63de8d627eda3d209-0 HTTP/1.1
,
Host: cdn4.appwork.org
,
Accept-Language: en_US
,
User-Agent: JDownloader/201707061810
,
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
,
Cache-Control: no-cache, no-store
,
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
,
Pragma: no-cache
,
Connection: Close
,
X-CDN-SIGNATURE-CHALLENGE: 59360292f0fe7069a68cedbae11a5746
,
cept-Encoding: identity
,
----------------Response Information------------
,
Connection-Time: 37ms
,
Request-Time: 47ms
,
----------------Response------------------------
,
HTTP/1.1 200 OK
,
Server: nginx/1.15.12
,
Date: Fri, 01 May 2020 09:22:34 GMT
,
Content-Type: application/octet-stream
,
Content-Length: 3357808
,
Connection: close
,
Last-Modified: Thu, 30 Apr 2020 16:57:55 GMT
,
ETag: "5eab0393-333c70"
,
X-Cache: HIT
,
X-CDN: 39_0_13_26
,
X-CDN-SIGNATURE: 59360292f0fe7069a68cedbae11a5746.Nanachi.59360292f0fe7069a68cedbae11a5746
,
Accept-Ranges: bytes
,
------------------------------------------------
,

,
,
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Connection ok. Downloaded /opt/JDownloader/tmp/update/JDU/updatePackage: 3357808 bytes,
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.UpdateClient(download) ] -> local file seems to be finished (size check ok),
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.UpdateClient(download) ] -> ... and hash is ok as well. perfect!,
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> AUTO_WRAPPED>
,
GET http://update.appwork.org/jcgi/track?rt=SO&jn=JDownloader.jar&pv=5&cv=2100000001&ping=&uid=1588324953796_335098313616786556_jds&pkh=12f1848a883e733ed40fffff0dae2f35&app=JDU&os=LINUX&arch=ARM&os64=0&jvm64=0&ct=Normal&data=%7B%22json%22%3A%22%7B%5C%22timeStamp%5C%22%3A1588324954109%2C%5C%22data%5C%22%3A%5C%22%7B%5C%5C%5C%22resume%5C%5C%5C%22%3Afalse%2C%5C%5C%5C%22expectedBytes%5C%5C%5C%22%3A3357
,
808%2C%5C%5C%5C%22clientRepo%5C%5C%5C%22%3A%5C%5C%5C%22JDownloader%2F201707061810%5C%5C%5C%22%2C%5C%5C%5C%22serverTag%5C%5C%5C%22%3A%5C%5C%5C%22nginx%2F1.15.12%5C%5C%5C%22%2C%5C%5C%5C%22cdnSignature%5C%5C%5C%22%3A%5C%5C%5C%22VALID%5C%5C%5C%22%2C%5C%5C%5C%22url%5C%5C%5C%22%3A%5C%5C%5C%22http%3A%2F%2Fcdn4.appwork.org%2FJDU%2F13908%2F1588265874234dc37ec8a2f9a29f1cd2b61d99e59d19a_094117506f03baa898f0a
,
8de63de8d627eda3d209-0%5C%5C%5C%22%2C%5C%5C%5C%22responseCode%5C%5C%5C%22%3A200%2C%5C%5C%5C%22timeStamp%5C%5C%5C%22%3A1588324954098%2C%5C%5C%5C%22duration%5C%5C%5C%22%3A15301%2C%5C%5C%5C%22responseBytes%5C%5C%5C%22%3A3357808%2C%5C%5C%5C%22resumeFrom%5C%5C%5C%22%3A0%2C%5C%5C%5C%22bytes%5C%5C%5C%22%3A3357808%2C%5C%5C%5C%22host%5C%5C%5C%22%3A%5C%5C%5C%22cdn4.appwork.org%5C%5C%5C%22%2C%5C%5C%5C%22logV
,
ersion%5C%5C%5C%22%3A1%2C%5C%5C%5C%22contentType%5C%5C%5C%22%3A%5C%5C%5C%22application%2Foctet-stream%5C%5C%5C%22%2C%5C%5C%5C%22status%5C%5C%5C%22%3A%5C%5C%5C%22OK%5C%5C%5C%22%7D%5C%22%2C%5C%22id%5C%22%3A1588324954147%2C%5C%22type%5C%22%3A%5C%22TRAFFIC_LOG%5C%22%7D%22%2C%22type%22%3A%22TRAFFIC_LOG%22%7D&1588324969412 via [Direct,
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(internalGetWithProxy) ] -> Get Try with Proxy Direct,
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> Connection OK: 2 Bytes loaded,
27|org.jdownloader.update.UpdateManager.log 5/1/20, 9:22:49 AM - INFO [ org.appwork.updatesys.client.defaultimpl.http.HttpClientImpl(info) ] -> AUTO_WRAPPED>
,

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

Looks like you forgot the '--restart=always' option (cf. https://github.com/jaymoulin/docker-jdownloader#docker or https://github.com/jaymoulin/docker-jdownloader#docker-compose) and to add your credentials with the `configure` command (https://github.com/jaymoulin/docker-jdownloader#environment-variables or preferably `docker exec jdownloader configure email@email.com password`)
