### ISSUE TITLE
jdownloader error in raspberry pi 4

### ISSUE THREAD

**Issue by Stephen988** [jaymoulin/docker-jdownloader#69]
Hi guys I can't use jdownloader on my raspberry pi 4, what is the error?
I have this at the end of long in portainer.
I can't see on myjdownloader webpage or in chrome extension my device

> 
>...
> java.lang.ExceptionInInitializerError
> 	at jd.SecondLevelLaunch$10$1.run(SecondLevelLaunch.java:784)
> Caused by: java.lang.RuntimeException: No Console Available!
> 	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
> 	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
> 	at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:118)
> 	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:107)
> 	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:32)
> 
> 	... 1 more

I need to attach other info?

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

I redacted a template for you to complete to be able to help you with this kind of trouble. Please don't ignore it for me to be able to help.

```
YOU HAVE TO READ THIS, YOUR ISSUE WILL BE IGNORED IF NOT READ AND RESPECTED.

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. Please be sure the issue you will report is not actually related to JDownloader.
If your issue is related to JDownloader, you will probably find help to the official
JDownloader forum (https://board.jdownloader.org/forumdisplay.php?f=50)
If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

PLEASE REMEMBER THAT I'M NOT PART OF JDOWNLOADER NOR DOCKER TEAMS!

REALLY IMPORTANT
As Jdownloader logs are REALLY verbose, always use <details><pre>PASTED LOGS</pre></details>
syntax to make your issue readable. As a reminder, I AM NOT PART OF THE JDOWNLOADER TEAMS
so if you're willing to paste your logs, you probably want to ask JDownloader support
at https://support.jdownloader.org/ (only if you didn't find help on their forum)

For more information about reporting issues, see
https://github.com/jaymoulin/docker-jdownloader/blob/master/CONTRIBUTING.md

You do NOT have to include this information if this is a FEATURE REQUEST

If you find this useful, please consider starring the repo and/or donating.
People showing interest attract more attention ;)
```

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
(paste your output here)
```

**Description**

```
Briefly describe the problem you are having in a few paragraphs.
```

**Command line I used to start the container**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
(paste logs)
</pre>
</details>

**Comment by Stephen988** [comment]
Hi @jaymoulin I don't know to find this output format, now I have reinstalled container in this way:

---
version: "2"
services:
   jdownloader:
    image: jaymoulin/jdownloader:latest
    container_name: jdownloader
    restart: unless-stopped
    user: 1001:100
    volumes:
        - /srv/dev-disk-by-label-KINGSTON_SA400S37120/appdata/jdownloader:/opt/JDownloader/cfg
        - /srv/dev-disk-by-label-Data-WD/NAS/Download:/opt/JDownloader/Downloads
    environment: 
            MYJD_USER: my email
            MYJD_PASSWORD: my password
            MYJD_DEVICE_NAME: raspi
    ports:
        - 3129:3129

now work perfectly, I don't know why past day won't work
