### ISSUE TITLE
OMV 5 with Pi4

### ISSUE THREAD

**Issue by starhopper1** [jaymoulin/docker-jdownloader#70]
Hi i got an Issue with the download bind its always writes the downloads on the internal sd card.
Its also shown in the web app that i have only 30gb free space(my sd card) and not some terrabyte
from my hardrive. the config binding works fine and is also on the harddrive and everything is written there. That why i am a bit confused tried different paths nothing worked.

/srv/dev-disk-by-label-Elements/config/jdownloader /opt/JDownloader/cfg

/srv/dev-disk-by-label-Elements/4k /opt/JDownloader/Downloads

the first is working and the config files are written, but if i download stuff its just writes here

/var/lib/docker/overlay2/bc8ae00f8249b10e8a18e97d9d490d047a19471627a434b4cdc48746a3fe0238/diff/srv/dev-disk-by-label-Elements/downloader/

![image](https://user-images.githubusercontent.com/35570376/82949747-6b304580-9fa4-11ea-991e-49cbb307c4d8.png)
![image](https://user-images.githubusercontent.com/35570376/82949774-784d3480-9fa4-11ea-9b5c-9fada19d0abe.png)

I also read the solved issue wich was the same but can´t replicate it on my case..^^ Dunno what i overlook..

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

I redacted a template for you to complete to be able to help you with this kind of trouble. Please don't ignore it for me to be able to help.

```
YOU HAVE TO READ THIS, YOUR ISSUE WILL BE IGNORED IF NOT READ AND RESPECTED.

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. Please be sure the issue you will report is not actually related to JDownloader.
If your issue is related to JDownloader, you will probably find help to the official
JDownloader forum (https://board.jdownloader.org/forumdisplay.php?f=50)
If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

PLEASE REMEMBER THAT I'M NOT PART OF JDOWNLOADER NOR DOCKER TEAMS!

REALLY IMPORTANT
As Jdownloader logs are REALLY verbose, always use <details><pre>PASTED LOGS</pre></details>
syntax to make your issue readable. As a reminder, I AM NOT PART OF THE JDOWNLOADER TEAMS
so if you're willing to paste your logs, you probably want to ask JDownloader support
at https://support.jdownloader.org/ (only if you didn't find help on their forum)

For more information about reporting issues, see
https://github.com/jaymoulin/docker-jdownloader/blob/master/CONTRIBUTING.md

You do NOT have to include this information if this is a FEATURE REQUEST

If you find this useful, please consider starring the repo and/or donating.
People showing interest attract more attention ;)
```

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
(paste your output here)
```

**Description**

```
Briefly describe the problem you are having in a few paragraphs.
```

**Command line I used to start the container**

THIS ONE IS PROBABLY THE MOST IMPORTANT IN YOUR CASE

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**

<details>
<pre>
(paste logs)
</pre>
</details>

**Comment by starhopper1** [comment]
So nvm.. i just testet the stack again, and i think maby i changened something but now it works.. no idea.. Sorry for the fals report.. but yesterday i changed the stack parameters like 10 times with the same result.. no idea why it works now.

**Comment by jaymoulin** [comment]
I'm glad you like my product and everything is running well. Please keep in mind that donation help me live and maintain this kind of product as encouraging me in this way.
