### ISSUE TITLE
umask is not working?

### ISSUE THREAD

**Issue by Troox73** [jaymoulin/docker-jdownloader#72]
Hi, using latest jaymoulin/jdownloader -> 1.4.0-amd64.
Image runs without umask option as it should. As soon as you set umask to 0775 it throws errors in Logfiles and quits.

Some short sample from log attached, can easyly reproduced. When you need a full log, np. Did i miss something or is it a jdownloader problem? Thanks for help!

[error.txt](https://github.com/jaymoulin/docker-jdownloader/files/4742816/error.txt)

**Comment by jaymoulin** [comment]
Your umask removes all rights for all users except for write right for other users. you probably want to use `0002` instead (cf. https://github.com/jaymoulin/docker-jdownloader#environment-variables and https://en.wikipedia.org/wiki/Umask#Mask_effect)

If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining and helping on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

**Comment by Troox73** [comment]
Okay, with umask 0002 it seems to work - after i set the right permissions to the created Dirs from jdownloader in /AppData/ (ENV Directorys) thanks!
