### ISSUE TITLE
Password env not being sanitized correctly

### ISSUE THREAD

**Issue by YellowTM** [jaymoulin/docker-jdownloader#73]
Password used: VTo@9W226ErM&f

MyJDownloadersettings.json had:

password" : "VTo@9W226ErM"password" : "VTo@9W226ErM"password" : "VTo@9W226ErM"password" : "",f",f",f",

I have since changed my password to alphanumeric which fixed it.

**Comment by jaymoulin** [comment]
Issue not well redacted. Looks like issue with `&` not being escaped from user side.
