### ISSUE TITLE
How to issue command to the container to restart jdownloader

### ISSUE THREAD

**Issue by H34dl3ss** [jaymoulin/docker-jdownloader#74]
Hi,
I tried to figure this out myself with the help of the jdownloader documentation mentioned here.
https://jdownloader.org/knowledge/wiki/terminal/index

When I issue a command this happens:
```
/opt/JDownloader # java -jar /opt/JDownloader/JDownloader.jar -status queue
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.appwork.shutdown.ShutdownController (file:/opt/JDownloader/JDownloader.jar) to field java.lang.ApplicationShutdownHooks.hooks
WARNING: Please consider reporting this to the maintainers of org.appwork.shutdown.ShutdownController
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO >> sun.Desktop: null
INFO >> XDG_CURRENT_DESKTOP: null
INFO >> KDE_FULL_SESSION: null
INFO >> KDE_SESSION_VERSION: null
INFO >> DESKTOP_SESSION: null
INFO >> GNOME_DESKTOP_SESSION_ID: null
INFO >> Prefer (merged) JSon Storage from File: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
...
and lots of other lines with some sort of output

```
I'm a bit lost with this, tbh.
All I want to achieve is, to send a command to the jdownloader to restart or to reconnect.
Something like:
`docker exec jdownloader_container jdownloader -restart`

Would you please give me some advice how to do this?
Thanks in advance!

**Comment by jaymoulin** [comment]
You can restart your container with the `docker restart jdownloader_container` command

**Comment by H34dl3ss** [comment]
OK, I knew that but i didn't know that would be the preferred solution!
Thank you!

**Comment by jaymoulin** [comment]
Using this command will send a SIGKILL to java, closing gracefully JDownloader.

Please keep in mind that maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).
