### ISSUE TITLE
Installation on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by kpietrek** [jaymoulin/docker-jdownloader#76]
Hello.
When trying to run JDownloader in docker according to of your guide:
`docker run -d --init --restart = always -v </ home / pietrek / Downloads>: / opt / JDownloader / Downloads -v </ home / pietrek / JDownloader / cfg>: / opt / JDownloader / cfg - name jdownloader -u $ (id -u) -p 3129: 3129 -e MYJD_USER=xxx@xxx.info -e MYJD_PASSWORD = xxx -e MYJD_DEVICE_NAME = pietrek jaymoulin / jdownloader`

I get the answer:
`-bash:: / opt / JDownloader / Downloads: No such file or directory`

After removing the <> characters, the container is created but unfortunately nothing is written in cfg and the application does not start.

Can I ask for a hint what to do to make it work?
I would like to add that it is only just beginning on this topic.

**Comment by jaymoulin** [comment]
There are way too much spaces in your command.

Should be 

`docker run -d --init --restart=always -v /home/pietrek/Downloads:/opt/JDownloader/Downloads -v /home/pietrek/JDownloader/cfg:/opt/JDownloader/cfg --name jdownloader -u $ (id -u) -p 3129:3129 -e MYJD_USER=xxx@xxx.info -e MYJD_PASSWORD=xxx -e MYJD_DEVICE_NAME=pietrek jaymoulin/jdownloader`
