### ISSUE TITLE
Extraction on Rpi 4 - still not working

### ISSUE THREAD

**Issue by tsvsj** [jaymoulin/docker-jdownloader#78]
To make this short: It seems that #75 is still not fixed. When checking the ExtractionExtension.log it shows 

`[org.jdownloader.extensions.extraction.multi.Multi(isAvailable)] -> Supported SevenZipJBinding|Version=4.65|RAR5=false|CPU_ARCH=ARM|OS_FAM=LINUX|OS=LINUX|64Bit_JVM=true|64Bit_ARCH=tru
e`

From my understanding the version should be 16.02 (https://sourceforge.net/projects/sevenzipjbind/files/7-Zip-JBinding/). Addtionally I'm wondering about `RAR5=false`. Is there anything we can do?

I've created a new container, based on the latest image version, 1.4.1:
```
# docker inspect jdownloader --format='{{index .Config.Labels.version}}'
1.4.1-arm64
```

Am I'm doing something wrong?

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

I don't personally own a RPI 4, therefore, I'll not be able to test that the added dependencies match the RAR5 archives format

**Comment by tsvsj** [comment]
Works like charm:
`[org.jdownloader.extensions.extraction.multi.Multi(isAvailable)] -> Supported SevenZipJBinding|Version=16.02-2.01|RAR5=true|CPU_ARCH=ARM|OS_FAM=LINUX|OS=LINUX|64Bit_JVM=true|64Bit_ARCH=true`

Thank you very much for your effort!
