### ISSUE TITLE
Has the direct connection mode it's own GUI?

### ISSUE THREAD

**Issue by joan-carles** [jaymoulin/docker-jdownloader#85]
Hi

I really believe the Direct connection mode is well configured. But the behaviour it's not probably the one I would wish in terms of privacy.

Once the Direct connection mode is working I try to connect to the Web interface using the URL of my host (192.168.1.210:3129) but I can't have access. Despite I don't like... probably this is the normal behaviour of the direct connection mode?

In other words I thought that direct connection mode would avoid to use myjdownloader server but seems not. Seems all the web interface, authentication process and so on always must be from the myjdownloader servers. And seems the utility of the direct connection mode is just avoid server in a few aspects. In conclusion If I'm not wrong Myjdownloader is not really a self-hosted service.

Is my understanding correct?

Thanks

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

JDownloader and MyJDownloader are two different products. To use JDownloader headless interface (used with this docker image), you need the use of MyJDownloader even with Direct Connection. 
JDownloader is this instance to download files. MyJdownloader is an external interface that provides API to use this headless server.
For further information on how JDownloader and MyJDownloader works, please contact JDownloader support : https://board.jdownloader.org/
