### ISSUE TITLE
umask problem

### ISSUE THREAD

**Issue by shanislav** [jaymoulin/docker-jdownloader#86]
Hello 
I set umask to docker-compose but it still doesn't work the way I want. Don't know what's wrong ? 
Thank you for your response.

My docker-compose file:
services:
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    user: 1000:1004
    volumes:
      - /root/dockers/jdownloader/config:/opt/JDownloader/cfg
      - /test:/opt/JDownloader/Downloads
      - /root/dockers/jdownloader/logs:/opt/JDownloader/logs #optional
      - /etc/localtime:/etc/localtime:ro #optional
    environment:
      MYJD_USER: ***@gmail.com #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      MYJD_PASSWORD: *** #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      MYJD_DEVICE_NAME: Test #optional
      XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads #optional
      UMASK: 0002
    ports:
      - 3129:3129
    networks:
      - dcbridge
networks:
  dcbridge:
    external: true

Downloaded file:

ls -la /test/
drwxrwxr-x   2 shano share      276 Jan  1 21:15  .
dr-xr-xr-x. 20 root  root        4096 Jan  1 21:11  ..
**-rw-r--r--**   1 shano share 17039945 Jan  1 21:14 'Comanchero MoonRay Video Clip 1984 (MCM) (288p_25fps_H264-96kbit_AAC).mp4'

Thanks

**Comment by fragkp** [comment]
Same issue here - I was able to solve the problem by set the umask as string.

```yaml
services:
    jdownloader:
        environment: 
            UMASK: "0002"
```
