### ISSUE TITLE
How to change the password of jDownloader in Docker?

### ISSUE THREAD

**Issue by rhodesfreak** [jaymoulin/docker-jdownloader#87]
Dear all,

I recently changed the password of my jDownloader account, could you please let me now how to proceed in Docker/OMV without the need to set it up again from scratch?

Thanks

**Comment by okeyishome** [comment]
You can edit your credentials by using the following command:

docker exec jdownloader configure your@email password

**Comment by rhodesfreak** [comment]
Hi,

Thanks for your help, but it's not working. I already tried this, but the password is not changing.

Any ideas?

**Comment by rhodesfreak** [comment]
Hi!

I tried again and it worked. :)

Thanks again
