### ISSUE TITLE
INFO >> CFG File does not exist: /opt/JDownloader/cfg/

### ISSUE THREAD

**Issue by Sammydlux** [jaymoulin/docker-jdownloader#88]
Hey Guys,

I tried the last few days with trying to run Jdownload on my Raspy 4, here is my setup:
RaspberryPi 4 
Image: Raspberry Pi OS Lite
Portainer running on OpenMediaVault 5

Everytime I deploy Jdownloader the logs are full of these warnings (full Logs are here: https://pastebin.com/gTtPVXg6):

> INFO >> CFG File does not exist: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json
> CFG File does not exist: /opt/JDownloader/cfg/org.jdownloader.update.lastchance.LastChanceConfig.json
> Caused by: java.io.IOException: Permission denied

This is my docker-compose:

> version: "2"
> services:
>    jdownloader:
>     image: jaymoulin/jdownloader
>     container_name: jdownloader
>     restart: always
>     user: 1002:100
>     volumes:
>         - /srv/dev-disk-by-uuid-b419ce77-bedc-4c2a-92bc-fb754f1f8d05/AppData/JDownloader:/opt/JDownloader/cfg
>         - /srv/dev-disk-by-uuid-b419ce77-bedc-4c2a-92bc-fb754f1f8d05/download:/opt/JDownloader/Downloads
>         - /srv/dev-disk-by-uuid-b419ce77-bedc-4c2a-92bc-fb754f1f8d05/AppData/JDownloader/Logs:/opt/JDownloader/logs #optional
>         - /etc/localtime:/etc/localtime:ro
>     environment: 
>             MYJD_USER: test25@web.de 
>             MYJD_PASSWORD: dummy
>             MYJD_DEVICE_NAME: Raspi
>     ports:
>         - 3129:3129 

The weird thing is that the folder that this docker-compose creats is set as root security group instead as the user 1002 (dockerUser)
My folder for the AppData is on a external harddrive if that helps

If anyone could help me here, I would be very happy.

**Comment by Sammydlux** [comment]
Lol... it works if I type everything manual in "create a container"

**Comment by Sammydlux** [comment]
I think I did some progress...
I created /opt/JDownloader manually and added the user group with:  

> sudo chown -R user:deployUsers /opt/JDownloader sudo chown -R user:deployUsers /opt/JDownloader

after creating the cointainer some Files are created in the AppData folder but not many...

These are the new logs [Logs](https://pastebin.com/GXSrBmjd)

**Comment by jaymoulin** [comment]
Please use issue template - I created it for a reason

You should use double quotes while adding your user id information (`user: "1002:100"`) for docker-compose to avoid any ambiguity (this should explain your incorrect user owner folder creation).

When your container is created, check that `/srv/dev-disk-by-uuid-b419ce77-bedc-4c2a-92bc-fb754f1f8d05/AppData/JDownloader//org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json` file contains your correct credentials. if not, correct it and restart (should automatically restart with your actual `docker-compose.yml` file)
