### ISSUE TITLE
Not an issue but very curious!!!! 

### ISSUE THREAD

**Issue by pb5050** [jaymoulin/docker-jdownloader#90]
I have the surface pro x and its my laptop / daily driver i love this thing 👌(❁´◡`❁)    (✿◡‿◡)

Aways its WIndows 10 ARM64.          is there any plans on making a release for this? i would really love and im sure others would too. just to scared to ask lol

**Comment by jaymoulin** [comment]
Arm64 arch is already supported and was fixed last time with the (1.4.2 release)[https://github.com/jaymoulin/docker-jdownloader/releases/tag/1.4.2]
