### ISSUE TITLE
rancher / kubernetes loop while updating => container crash

### ISSUE THREAD

**Issue by Schmandre** [jaymoulin/docker-jdownloader#91]
**Description**

Rancher / Kubernetes Workload, not able to post this here. Just translated docker-compose

**Steps to reproduce the issue:**
1. Spin up the container inside the rancher / kubernetes workload
2. Take a look into logs
3. System doing update and recreate the container, after a few recreates it say "Crashed"

**Comment by spongebob33** [comment]
Hi, I have the same issue.
I did the same as you and it crash after a few attempts at updating the container.

**Comment by the4anoni** [comment]
I have same problem with Docker and Portainer.
Every time jdownloader updates it shuts down, I need to reboot container to make it work again, this is annonying.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Running in Portainer in a single instance swarm, just keeps updating and restarting.

**Comment by jaymoulin** [comment]
Please follow issue template and documentation (identify part is mandatory - https://github.com/jaymoulin/docker-jdownloader#identify) /nobody can/will help you with the lack of information
