### ISSUE TITLE
Continuous restart of the container after installation.

### ISSUE THREAD

**Issue by kpietrek** [jaymoulin/docker-jdownloader#93]
Please remove.

I've already dealt with it.

**Comment by trulow** [comment]
Can you fill us in as to what you did to fix it?

**Comment by jaymoulin** [comment]
>I installed the container using this line:

>docker run -d --init --restart=always -v /opt/JDownloader/Downloads -v /opt/JDownloader/cfg --name jdownloader -u $(id -u) -p 3129:3129 -e MYJD_USER=pietrek@***.info -e MYJD_PASSWORD=*** -e MYJD_DEVICE_NAME=pietrek jaymoulin/jdownloader

>After installation, the container has a problem with starting up correctly. The container is restarted continuously.

>What is wrong? Should I check and make it work?

I think he forgot to put his credentials - documentation : https://github.com/jaymoulin/docker-jdownloader#identify
