### ISSUE TITLE
Can't install Event Scripter Extension

### ISSUE THREAD

**Issue by Erik262** [jaymoulin/docker-jdownloader#95]
**Command line I used to start the container**
I just used the instruction command

**Steps to reproduce the issue:**
1. try to install Event Scripter

**Describe the results you received:**
I'm getting an "install/loading" animation that Event Scripter is installing right now, but it takes obviously too long.

**Describe the results you expected:**
An installed and working Event Scripter

**Additional information you deem important (e.g. issue happens only occasionally):**
Had this issue even with very old versions of this docker container.

**Provide some logs (`docker logs jdownloader`)**

I'm sorry, I don't know how to provide them here and where I can get them, but I would provide them, if you tell me how :)

**Comment by Erik262** [comment]
Well, this problem disappeared after restarting the docker container many times and doing a lot of updates.

**Comment by jaymoulin** [comment]
Probably fixed with the latest 2.0.1 image even if not related - Maybe check with offical JDownloader support as I don't use event scripter and seems unrelated to a docker behaviour.

To provide logs, just copy/past the given command (`docker logs jdownloader`)
