### ISSUE TITLE
Access to Host:3129

### ISSUE THREAD

**Issue by titou4307** [jaymoulin/docker-jdownloader#97]
Hello

I have made install into Docker of this package
The host is a Raspberry PI4 8Go

I cannot access to the web interface like adress IP:3129 (xxx.xxx.xxx.xxx:3129)

I have understanding the port 3129 may be open in the router for to access from internet to the host with this docker container

May be I have not understand all ??

**Comment by DanielVolz** [comment]
I don't think it is possible.

**Comment by jaymoulin** [comment]
No, it's not possible with this docker image because it's not its purpose, but this is technically possible
